date: 20251211
food:
  - time: 20251211053300
    name: 桔柚
    amount: 150
    unit: g

  - time: 20251211053600
    name: 馒头2512a
    amount: 1
    unit: 个
  - time: 20251211053600
    name: 豆瓣龙利鱼2512a
    amount: 50.0
    unit: g
  - time: 20251211053600
    name: 南瓜
    amount: 70
    unit: g
  - time: 20251211053600
    name: 西兰苔
    amount: 65
    unit: g

  - time: 20251211055100
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251211055100
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251211055100
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251211055900
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251211055900
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251211120900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251211120900
    name: 东棘沙棘原浆
    amount: 30
    unit: g
  - time: 20251211120900
    name: 百香果
    amount: 48.0
    unit: g

  - time: 20251211121200
    name: 大米
    amount: 40.0
    unit: g
  - time: 20251211121200
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20251211121200
    name: 紫米
    amount: 15.0
    unit: g
  - time: 20251211121200
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20251211121200
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20251211121200
    name: 烤叉烧2512a
    amount: 30
    unit: g
  - time: 20251211121200
    name: 油菜
    amount: 180
    unit: g
  - time: 20251211121200
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g

  - time: 20251211123900
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251211123900
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
    
  - time: 20251211234500
    name: 梨
    amount: 250
    unit: g

  - time: 20251211220000
    name: 山药豆
    amount: 60
    unit: g
  - time: 20251211220000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20251211220000
    name: 油菜
    amount: 120
    unit: g
  - time: 20251211220000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251211220000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g
    
  - time: 20251211055000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251211055000
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251211041700
    name: 开水
    amount: 200
    unit: ml
  - time: 20251211052100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251211055900
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251211062000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251211081100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251211085900
    name: 开水
    amount: 250
    unit: ml
  - time: 20251211100100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251211123900
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20251211141000
    name: 开水
    amount: 250
    unit: ml

  - time: 20251211055000
    name: 可可奶
    amount: 120.0
    unit: ml
  - time: 20251211202800
    name: 开水
    amount: 130
    unit: ml
med:
  - time: 20251211055900
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251211062000
    name: selenium
    amount: 200
    unit: μg
  - time: 20251211062000
    name: mature multi
    amount: 1
    unit: 片
  - time: 20251211062000
    name: 维生素C
    amount: 2.0
    unit: g
log: |
comment: |