date: 20260215
food:
  - time: 20260215051700
    name: 番石榴
    amount: 155
    unit: g

  - time: 20260215052100
    name: 萝卜糕2602a
    amount: 180
    unit: g
  - time: 20260215052100
    name: 山药
    amount: 90
    unit: g
  - time: 20260215052100
    name: 南瓜
    amount: 45
    unit: g
  - time: 20260215052100
    name: 红菜苔
    amount: 150
    unit: g
  - time: 20260215052100
    name: 十三村原味腐乳
    amount: 7.5
    unit: g

  - time: 20260215053700
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260215053700
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260215053700
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260215054500
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260215054500
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260215135800
    name: 番茄酱
    amount: 25
    unit: g
  - time: 20260215135800
    name: 戈壁密码有机沙棘原浆
    amount: 25
    unit: g
  - time: 20260215135800
    name: 菊粉
    amount: 10.0
    unit: g

  - time: 20260215135900
    name: 猕猴桃
    amount: 65
    unit: g
  - time: 20260215135900
    name: 柿子
    amount: 130
    unit: g

  - time: 20260215140300
    name: 一品寒香大米
    amount: 65.0
    unit: g
  - time: 20260215140300
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20260215140300
    name: 红豆
    amount: 10.0
    unit: g
  - time: 20260215140300
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20260215140300
    name: 腌鸡腿肉2602a
    amount: 169.0
    unit: g
  - time: 20260215140300
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20260215140300
    name: 油菜
    amount: 230
    unit: g
  - time: 20260215140300
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260215140300
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260215142700
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260215142700
    name: 品儿Piner天然可可粉
    amount: 3
    unit: g
water:
  - time: 20260215035800
    name: 开水
    amount: 200
    unit: ml
  - time: 20260215050000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260215054500
    name: 咖啡
    amount: 103.5
    unit: ml
  - time: 20260215061900
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260215070300
    name: 红茶
    amount: 250
    unit: ml
  - time: 202602150075100
    name: 红茶
    amount: 250
    unit: ml
  - time: 202602150084100
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260215143700
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260215142700
    name: 可可奶
    amount: 100.0
    unit: ml
  - time: 20260215152500
    name: 红茶
    amount: 200
    unit: ml
med:
  - time: 20260215054500
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260215061900
    name: selenium
    amount: 200
    unit: μg
  - time: 20260215061900
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
