date: 20251219
food:
  - time: 20251219031400
    name: 猕猴桃
    amount: 95
    unit: g

  - time: 20251219044200
    name: 馒头2512b
    amount: 1
    unit: 个
  - time: 20251219044200
    name: 南瓜
    amount: 120
    unit: g
  - time: 20251219044200
    name: 西兰苔
    amount: 130
    unit: g
  - time: 20251219044200
    name: 卤牛肉2512a
    amount: 60
    unit: g

  - time: 20251219033300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251219033300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251219033300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251219034100
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251219034100
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251219090600
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251219090600
    name: 东棘沙棘原浆
    amount: 30
    unit: g
  - time: 20251219090600
    name: 百香果
    amount: 0
    unit: g
  - time: 20251219090600
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20251219090700
    name: 柿子
    amount: 95
    unit: g

  - time: 20251219091100
    name: 大米
    amount: 40.0
    unit: g
  - time: 20251219091100
    name: 紫米
    amount: 15.0
    unit: g
  - time: 20251219091100
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20251219091100
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20251219091100
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20251219091100
    name: 益佳龙广式烧鸭
    amount: 80
    unit: g
  - time: 20251219091100
    name: 豌豆苗
    amount: 160
    unit: g
  - time: 20251219091100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g

  - time: 20251219094300
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251219094300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251219220000
    name: 山药豆
    amount: 50
    unit: g
  - time: 20251219220000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20251219220000
    name: 红菜苔
    amount: 120
    unit: g
  - time: 20251219220000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251219220000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251219055000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251219055000
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251219020700
    name: 开水
    amount: 200
    unit: ml
  - time: 20251219030300
    name: 开水
    amount: 250
    unit: ml
  - time: 20251219034100
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251219044200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251219051400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251219065000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251219081000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251219094300
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20251219123400
    name: 开水
    amount: 250
    unit: ml

  - time: 20251219161200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251219055000
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20251219202800
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20251219034100
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251219044200
    name: selenium
    amount: 200
    unit: μg
  - time: 20251219044200
    name: mature multi
    amount: 1
    unit: 片
  - time: 20251219090600
    name: 维生素C
    amount: 1
    unit: g
log: |
comment: |