date: 20250720
food:
  - time: 20250720100600
    name: 梨
    amount: 250
    unit: g

  - time: 20250720101000
    name: 裕湘A+细挂面
    amount: 40.0
    unit: g
  - time: 20250720112700
    name: 黑胡椒风味芊芊鱼排
    amount: 65
    unit: g
  - time: 20250720101000
    name: 油菜
    amount: 60
    unit: g
  - time: 20250720101000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250720101000
    name: 香油
    amount: 1.0
    unit: g

  - time: 20250720102300
    name: 红塔玫瑰黄油饼
    amount: 25
    unit: g
  - time: 20250720102300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250720102300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250720102300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250720103700
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250720103700
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250720191000
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250720191000
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250720191000
    name: 菊粉
    amount: 5.0
    unit: g
  - time: 20250720191000
    name: 百香果
    amount: 40
    unit: g

  - time: 20250720191800
    name: 扬农沁香米
    amount: 30
    unit: g
  - time: 20250720191800
    name: 泉嫁艳青麦仁
    amount: 40
    unit: g
  - time: 20250720191800
    name: 腌鸡腿肉2507a
    amount: 50
    unit: g
  - time: 20250720191800
    name: 菜心
    amount: 220
    unit: g
  - time: 20250720191800
    name: 木耳
    amount: 10
    unit: g
  - time: 20250720191800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250720191800
    name: 油
    amount: 0.5
    unit: g

  - time: 20250720194200
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250720194200
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
  
  - time: 20250720191100
    name: 李子
    amount: 160
    unit: g   

  - time: 20250720180000
    name: 馒头2507c
    amount: 1
    unit: 个
  - time: 20250720180000
    name: 粉蒸肉2507b
    amount: 60
    unit: g
  - time: 20250720180000
    name: 油菜
    amount: 120
    unit: g
  - time: 20250720180000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250720180000
    name: 油
    amount: 0.5
    unit: g

  - time: 20250720190000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250720190000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250720084200
    name: 开水
    amount: 200
    unit: ml
  - time: 20250720094800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250720101000
    name: 汤水
    amount: 500
    unit: ml
  - time: 20250720103700
    name: 咖啡
    amount: 81.5
    unit: ml
  - time: 20250720111500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250720122400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250720141000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250720164000
    name: 开水
    amount: 300
    unit: ml
  - time: 20250720194200
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250720212000
    name: 开水
    amount: 220
    unit: ml
  - time: 20250720190000
    name: 可可奶
    amount: 80
    unit: ml
med:
  - time: 20250720103700
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250720111500
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20250720111500
    name: selenium
    amount: 200
    unit: μg
  - time: 20250720111500
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
