date: 20260207
food:
  - time: 20260207055900
    name: 番石榴
    amount: 150
    unit: g
  - time: 20260207055900
    name: 香蕉
    amount: 150
    unit: g

  - time: 20260207060300
    name: 塞北雪龙须挂面
    amount: 120.0
    unit: g
  - time: 20260207060300
    name: 鸡肉
    amount: 150
    unit: g
    log: 实际是开封桶子鸡
  - time: 20260207060300
    name: 黄心菜
    amount: 60
    unit: g
  - time: 20260207060300
    name: 中盐绿色低钠湖盐
    amount: 2.0
    unit: g
    log: 桶子鸡含盐折算2.0g。
  - time: 20260207060300
    name: 味精
    amount: 0.5
    unit: g

  - time: 20260207055900
    name: 榄仁手工沙琪玛
    amount: 125
    unit: g
  - time: 20260207055900
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260207055900
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260207055900
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260207065400
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260207065400
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260207114500
    name: 番茄酱
    amount: 20
    unit: g
  - time: 20260207114500
    name: 戈壁密码有机沙棘原浆
    amount: 20
    unit: g
  - time: 20260207114500
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20260207114600
    name: 猕猴桃
    amount: 65
    unit: g
  - time: 20260207114800
    name: 桔柚
    amount: 95
    unit: g

  - time: 20260207115100
    name: 萝卜糕2602a
    amount: 250
    unit: g
  - time: 20260207065400
    name: 维扬破碎油方
    amount: 0
    unit: g
  - time: 20260207115100
    name: 黄心菜
    amount: 235.0
    unit: g
  - time: 20260207115100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260207115100
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260207115100
    name: 驼铃风干甜红葡萄酒
    amount: 28.0
    unit: g
  - time: 20260207115100
    name: 林沐祈黄鱼酥
    amount: 28
    unit: g
  - time: 20260207121700
    name: 河套纯牛奶粉
    amount: 26.5
    unit: g
  - time: 20260207121700
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260207044900
    name: 开水
    amount: 200
    unit: ml
  - time: 20260207054800
    name: 开水
    amount: 250
    unit: ml
  - time: 20260207060300
    name: 汤水
    amount: 450.0
    unit: ml
  - time: 20260207065400
    name: 咖啡
    amount: 101.0
    unit: ml
  - time: 20260207075100
    name: 开水
    amount: 250
    unit: ml
  - time: 20260207082300
    name: 开水
    amount: 250
    unit: ml
  - time: 20260207093300
    name: 开水
    amount: 250
    unit: ml
  - time: 20260207121700
    name: 可可奶
    amount: 100.0
    unit: ml
  - time: 20260207163000
    name: 开水
    amount: 150
    unit: ml
med:
  - time: 20260207065400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260207075100
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20260207075100
    name: selenium
    amount: 200
    unit: μg
  - time: 20260207075100
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
