date: 20260221
food:
  - time: 20260221062400
    name: 释迦果
    amount: 100
    unit: g

  - time: 20260221062900
    name: 塞北雪龙须挂面
    amount: 120.0
    unit: g
  - time: 20260221062900
    name: 猪蹄筋
    amount: 110
    unit: g
    log: 实际是猪元宝、猪窝骨
  - time: 20260221062900
    name: 楚郡味豆瓣酱
    amount: 20
    unit: g
  - time: 20260221062900
    name: 维扬破碎油方
    amount: 40
    unit: g
  - time: 20260221062900
    name: 油菜
    amount: 50
    unit: g

  - time: 20260221065300
    name: 凤城鸡仔饼
    amount: 15.0
    unit: g
  - time: 20260221065300
    name: 新疆手工切糕
    amount: 35.0
    unit: g
  - time: 20260221065300
    name: 徽韵棠原味黄山烧饼
    amount: 20
    unit: g
  - time: 20260221065300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260221065300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260221065300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260221070700
    name: 河套纯牛奶粉
    amount: 25.0
    unit: g
  - time: 20260221070700
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260221171700
    name: 番茄酱
    amount: 25
    unit: g
  - time: 20260221171700
    name: 戈壁密码有机沙棘原浆
    amount: 25
    unit: g
  - time: 20260221171700
    name: 菊粉
    amount: 15
    unit: g

  - time: 20260221171800
    name: 苹果
    amount: 150
    unit: g
    
  - time: 20260221172000
    name: 黑米饭2505a
    amount: 200
    unit: g
  - time: 20260221115100
    name: 油菜
    amount: 200
    unit: g
  - time: 20260221115100
    name: 木耳
    amount: 10
    unit: g
  - time: 20260221115100
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20260221115100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260221115100
    name: 欧丽薇兰橄榄油
    amount: 1.0
    unit: g

  - time: 20260221182500
    name: 柿子
    amount: 280
    unit: g

  - time: 20260221183500
    name: 河套纯牛奶粉
    amount: 25.0
    unit: g
  - time: 20260221183500
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260221052400
    name: 开水
    amount: 100
    unit: ml
  - time: 20260221060700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260221062900
    name: 汤水
    amount: 500
    unit: ml
  - time: 20260221070700
    name: 咖啡
    amount: 100.0
    unit: ml
  - time: 20260221074800
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260221083300
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260221091000
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260221093900
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260221114100
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260221114100
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260221151800
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260221182900
    name: 汤水
    amount: 300
    unit: ml
  - time: 20260221183500
    name: 可可奶
    amount: 100.0
    unit: ml
  - time: 20260221200400
    name: 红茶
    amount: 200
    unit: ml
med:
  - time: 20260221070700
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260221074800
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20260221074800
    name: selenium
    amount: 200
    unit: μg
  - time: 20260221074800
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
