date: 20250702
food:
  - time: 20250702072400
    name: 黄桃
    amount: 113.5
    unit: g

  - time: 20250702072700
    name: 馒头2507a
    amount: 1
    unit: 个
  - time: 20250702072700
    name: 南瓜
    amount: 42.0
    unit: g
  - time: 20250702190100
    name: 卤牛肚2506b
    amount: 50
    unit: g
  - time: 20250702190100
    name: 粉蒸肉2507a
    amount: 0
    unit: g
  - time: 20250702072700
    name: 芦笋
    amount: 115
    unit: g
  - time: 20250702072700
    name: 中盐绿色低钠湖盐
    amount: 0.5
    unit: g

  - time: 20250702073600
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250702073600
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250702073600
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250702075100
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250702075100
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250702131800
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250702131800
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250702131800
    name: 艾斯蔗菊粉
    amount: 10
    unit: g

  - time: 20250702132000
    name: 杏
    amount: 127.0
    unit: g
    log:
      - 崂山蜜杏43.5g
      - 荷兰香蜜杏83.5g  

  - time: 20250702132500
    name: 扬农沁香米
    amount: 40
    unit: g
  - time: 20250702132500
    name: 福润东方有机小米
    amount: 30
    unit: g
  - time: 20250702132500
    name: 泉嫁艳青麦仁
    amount: 50
    unit: g
  - time: 20250702132500
    name: 腌鸡腿肉2504b
    amount: 60
    unit: g
  - time: 20250702132500
    name: 木耳
    amount: 10
    unit: g
  - time: 20250702132500
    name: 菜心
    amount: 175
    unit: g
  - time: 20250702132500
    name: 胡萝卜
    amount: 100
    unit: g
  - time: 20250702132500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250702132500
    name: 油
    amount: 0.5
    unit: g

  - time: 20250702140000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250702140000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250702190700
    name: 圣女果
    amount: 210.5
    unit: g
    log:
      - 糖珀琥97.5g
      - 青甜2号113.0g

  - time: 20250702191200
    name: 土豆
    amount: 150
    unit: g
  - time: 20250702191200
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250702191200
    name: 油菜
    amount: 150
    unit: g
  - time: 20250702191200
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250702191200
    name: 油
    amount: 0.5
    unit: g

  - time: 20250702194200
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250702194200
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250702061600
    name: 开水
    amount: 200
    unit: ml
  - time: 20250702071100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250702072700
    name: 粥水
    amount: 500
    unit: ml
  - time: 20250702075100
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250702083300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250702093300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250702103000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250702140000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250702145500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250702170400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250702194200
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250702201000
    name: 开水
    amount: 125
    unit: ml
med:
  - time: 20250702075100
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250702083300
    name: selenium
    amount: 200
    unit: μg
  - time: 20250702083300
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
