date: 20251207
food:
  - time: 20251207194100
    name: 苹果
    amount: 137.0
    unit: g

  - time: 20251207194500
    name: 馒头2512a
    amount: 1
    unit: 个
  - time: 20251207194500
    name: 龙利鱼肉
    amount: 60
    unit: g
  - time: 20251207194500
    name: 南瓜
    amount: 75
    unit: g
  - time: 20251207194500
    name: 象大厨北豆腐
    amount: 0
    unit: g
  - time: 20251207194500
    name: 西兰苔
    amount: 140.0
    unit: g
  - time: 20251207194500
    name: 十三村原味腐乳
    amount: 8.0
    unit: g

  - time: 20251207201100
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251207201100
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251207201100
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251207202400
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251207202400
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20251207234400
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251207234400
    name: 东棘沙棘原浆
    amount: 30
    unit: g
  - time: 20251207234400
    name: 百香果
    amount: 48.0
    unit: g
  - time: 20251207234400
    name: 菊粉
    amount: 10.0
    unit: g

  - time: 20251207234500
    name: 桔柚
    amount: 150
    unit: g

  - time: 20251207235200
    name: 扬农沁香米
    amount: 70
    unit: g
  - time: 20251207235200
    name: 紫米
    amount: 20
    unit: g
  - time: 20251207235200
    name: 绿豆
    amount: 10
    unit: g
  - time: 20251207235200
    name: 木耳
    amount: 10
    unit: g
  - time: 20251207235200
    name: 烤叉烧2511b
    amount: 50
    unit: g
  - time: 20251207235200
    name: 油菜
    amount: 200
    unit: g
  - time: 20251207235200
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20251207235200
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251207201200
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251207201200
    name: 品儿Piner天然可可粉
    amount: 4.5
    unit: g
water:
  - time: 20251207181800
    name: 开水
    amount: 200
    unit: ml
  - time: 20251207191100
    name: 开水
    amount: 220
    unit: ml
  - time: 20251207194500
    name: 汤水
    amount: 500
    unit: ml
  - time: 20251207202400
    name: 咖啡
    amount: 121.0
    unit: ml
  - time: 20251207211600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251207223600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251207234300
    name: 开水
    amount: 250
    unit: ml
  - time: 20251207023600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251207201200
    name: 可可奶
    amount: 120.0
    unit: ml
  - time: 20251207202800
    name: 开水
    amount: 130
    unit: ml
med:
  - time: 20251207202400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251207211600
    name: selenium
    amount: 200
    unit: μg
  - time: 20251207211600
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
