date: 20250709
food:
  - time: 20250709085200
    name: 橙
    amount: 130
    unit: g
    
  - time: 20250709085800
    name: 海带
    amount: 5
    unit: g
  - time: 20250709085800
    name: 绿豆
    amount: 30
    unit: g
  - time: 20250709085800
    name: 泉嫁艳青麦仁
    amount: 20
    unit: g
  - time: 20250709085800
    name: 蜂蜜
    amount: 20
    unit: g
  - time: 20250709085800
    name: 南瓜
    amount: 55
    unit: g
  - time: 20250709190100
    name: 广信酱油鲭鱼
    amount: 70
    unit: g
  - time: 20250709085800
    name: 芦笋
    amount: 145.0
    unit: g

  - time: 20250709093000
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250709093000
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250709093000
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250709094700
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250709094700
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250709135300
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250709135300
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250709135300
    name: 艾斯蔗菊粉
    amount: 10
    unit: g

  - time: 20250709135400
    name: 李子
    amount: 80.0
    unit: g
  - time: 20250709135500
    name: 杏
    amount: 53.5
    unit: g

  - time: 20250709135800
    name: 扬农沁香米
    amount: 30
    unit: g
  - time: 20250709135800
    name: 福润东方有机小米
    amount: 20
    unit: g
  - time: 20250709135800
    name: 泉嫁艳青麦仁
    amount: 40
    unit: g
  - time: 20250709135800
    name: 油菜
    amount: 120
    unit: g
  - time: 20250709135800
    name: 胡萝卜
    amount: 100
    unit: g
  - time: 20250709135800
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250709135800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250709135800
    name: 油
    amount: 0.5
    unit: g

  - time: 20250709143800
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250709143800
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
    
  - time: 20250709182000
    name: 圣女果
    amount: 153
    unit: g
    
  - time: 20250709183000
    name: 馒头2507b
    amount: 1
    unit: 个
  - time: 20250709183000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250709183000
    name: 油菜
    amount: 50
    unit: g
  - time: 20250709183000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250709183000
    name: 油
    amount: 0.5
    unit: g
  
  - time: 20250709193000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250709193000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250709073700
    name: 开水
    amount: 200
    unit: ml
  - time: 20250709084100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250709094700
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250709111500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250709123300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250709143800
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20250709160300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250709171400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250709193000
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250709193500
    name: 开水
    amount: 150
    unit: ml
med:
  - time: 20250709094700
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250709111500
    name: selenium
    amount: 200
    unit: μg
  - time: 20250709111500
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
