date: 20250721
food:
  - time: 20250721074300
    name: 梨
    amount: 250
    unit: g

  - time: 20250721074900
    name: 馒头2507c
    amount: 1
    unit: 个
  - time: 20250721112700
    name: 卤牛肚2507a
    amount: 50
    unit: g
  - time: 20250721074900
    name: 南瓜
    amount: 65
    unit: g
  - time: 20250721074900
    name: 芦笋
    amount: 150
    unit: g

  - time: 20250721080300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250721080300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250721080300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250721084000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250721084000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250721124300
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250721124300
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250721124300
    name: 菊粉
    amount: 6.0
    unit: g
  - time: 20250721124300
    name: 百香果
    amount: 40
    unit: g

  - time: 20250721124500
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20250721124500
    name: 泉嫁艳青麦仁
    amount: 50.0
    unit: g
  - time: 20250721124500
    name: 腌鸡腿肉2507a
    amount: 65
    unit: g
  - time: 20250721124500
    name: 快菜
    amount: 200
    unit: g
  - time: 20250721124500
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20250721124500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250721124500
    name: 油
    amount: 0.5
    unit: g

  - time: 20250721132400
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250721132400
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250721211000
    name: 李子
    amount: 160
    unit: g

  - time: 20250721211500
    name: 土豆
    amount: 250
    unit: g
  - time: 20250721211500
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250721211500
    name: 油菜
    amount: 145.0
    unit: g
  - time: 20250721211500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250721211500
    name: 油
    amount: 0.5
    unit: g

  - time: 20250721222900
    name: 红塔玫瑰黄油饼
    amount: 0
    unit: g
  - time: 20250721223200
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250721223200
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250721063000
    name: 开水
    amount: 200
    unit: ml
  - time: 20250721073000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250721084000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250721095600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250721105600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250721132400
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250721143500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250721161700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250721223200
    name: 可可奶
    amount: 80.0
    unit: ml
med:
  - time: 20250721084000
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250721095600
    name: selenium
    amount: 200
    unit: μg
  - time: 20250721095600
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
