date: 20260210
food:
  - time: 20260210045800
    name: 番石榴
    amount: 150
    unit: g
  - time: 20260210050000
    name: 香蕉
    amount: 115
    unit: g

  - time: 20260210050500
    name: 塞北雪龙须挂面
    amount: 120.0
    unit: g
  - time: 20260210050500
    name: 鸡肉
    amount: 160
    unit: g
    log: 实际是开封桶子鸡
  - time: 20260210050500
    name: 黄心菜
    amount: 70
    unit: g
  - time: 20260210050500
    name: 中盐绿色低钠湖盐
    amount: 2.0
    unit: g
    log: 桶子鸡含盐折算2.0g。
  - time: 20260210050500
    name: 味精
    amount: 0.5
    unit: g

  - time: 20260210052900
    name: 榄仁手工沙琪玛
    amount: 60
    unit: g
  - time: 20260210052900
    name: 黄吉利苕丝糖
    amount: 20
    unit: g
  - time: 20260210052900
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260210052900
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260210052900
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260210061600
    name: 河套纯牛奶粉
    amount: 25.0
    unit: g
  - time: 20260210061600
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260210141000
    name: 番茄酱
    amount: 23.0
    unit: g
  - time: 20260210141000
    name: 戈壁密码有机沙棘原浆
    amount: 20
    unit: g
  - time: 20260210141000
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20260210141200
    name: 猕猴桃
    amount: 63.0
    unit: g

  - time: 20260210141600
    name: 一品寒香大米
    amount: 60
    unit: g
  - time: 20260210141600
    name: 胡萝卜
    amount: 80
    unit: g
  - time: 20260210141600
    name: 韩三顺辣白菜
    amount: 40
    unit: g
  - time: 20260210141600
    name: 枸杞
    amount: 5
    unit: g
  - time: 20260210141600
    name: 楚郡味豆瓣酱
    amount: 10
    unit: g
  - time: 20260210115100
    name: 猪蹄筋
    amount: 0
    unit: g
  - time: 20260210115100
    name: 卤牛肉2601a
    amount: 50
    unit: g
  - time: 20260210115100
    name: 红菜苔
    amount: 200
    unit: g
  - time: 20260210115100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260210115100
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260210143200
    name: 榄仁手工沙琪玛
    amount: 60
    unit: g
  - time: 20260210143200
    name: 河套纯牛奶粉
    amount: 25.0
    unit: g
  - time: 20260210143200
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260210033000
    name: 开水
    amount: 200
    unit: ml
  - time: 20260210042800
    name: 开水
    amount: 250
    unit: ml
  - time: 20260210050500
    name: 汤水
    amount: 450.
    unit: ml
  - time: 20260210141600
    name: 酸奶
    amount: 90.0
    unit: ml
    log: 减掉200g
  - time: 20260210060700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260210083000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260210095000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260210120000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260210143200
    name: 可可奶
    amount: 100.0
    unit: ml
  - time: 20260210173700
    name: 开水
    amount: 150
    unit: ml
med:
  - time: 20260210141600
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260210060700
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20260210060700
    name: selenium
    amount: 200
    unit: μg
  - time: 20260210060700
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
