date: 20250621
food:
  - time: 20250621080300
    name: 人参果
    amount: 128.5
    unit: g
  - time: 20250621080700
    name: 馒头2506b
    amount: 1
    unit: 个
  - time: 20250621080700
    name: 南瓜
    amount: 38.5
    unit: g
  - time: 20250621190100
    name: 粉蒸肉2506a
    amount: 116.5
    unit: g
  - time: 20250621080700
    name: 秋葵
    amount: 158.5
    unit: g
  - time: 20250621082600
    name: 闽宋唐咸绿豆饼
    amount: 36.5
    unit: g
  - time: 20250621082600
    name: 闽宋唐甜绿豆饼
    amount: 40.0
    unit: g
  - time: 20250621082600
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250621082600
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250621082600
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g
  - time: 20250621084200
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250621084200
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250621130300
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250621130300
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250621130300
    name: 菊粉
    amount: 14.0
    unit: g

  - time: 20250621130500
    name: 李子
    amount: 135
    unit: g
    
  - time: 20250621130900
    name: 益奇多燕麦片
    amount: 10.0
    unit: g
  - time: 20250621130900
    name: 扬农沁香米
    amount: 10.0
    unit: g
  - time: 20250621130900
    name: 福润东方有机小米
    amount: 20.0
    unit: g
  - time: 20250621130900
    name: 泉嫁艳青麦仁
    amount: 30.0
    unit: g
  - time: 20250621130900
    name: 海带
    amount: 5
    unit: g
  - time: 20250621130900
    name: 蜂蜜
    amount: 20.0
    unit: g
  - time: 20250621130900
    name: 土豆
    amount: 100
    unit: g
  - time: 20250621130900
    name: 三都港黄鱼鯗
    amount: 160
    unit: g
  - time: 20250621130900
    name: 菜心
    amount: 150
    unit: g
  - time: 20250621130900
    name: 胡萝卜
    amount: 100
    unit: g
  - time: 20250621130900
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250621130900
    name: 油
    amount: 1.0
    unit: g

  - time: 20250621140000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250621140000
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20250621182600
    name: 橙
    amount: 125
    unit: g


  - time: 20250621183000
    name: 裕湘A+细挂面
    amount: 100
    unit: g
  - time: 20250621183000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250621183000
    name: 油菜
    amount: 100
    unit: g
  - time: 20250621183000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250621183000
    name: 味精
    amount: 0.5
    unit: g
  - time: 20250621183000
    name: 油
    amount: 0.5
    unit: g

  - time: 20250621190800
    name: 闽宋唐咸绿豆饼
    amount: 40
    unit: g
  - time: 20250621190800
    name: 闽宋唐甜绿豆饼
    amount: 40
    unit: g
  - time: 20250621190800
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250621190800
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250621064900
    name: 开水
    amount: 200
    unit: ml
  - time: 20250621074800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250621084200
    name: 咖啡
    amount: 82.0
    unit: ml
  - time: 20250621100300
    name: 开水
    amount: 250
    unit: ml

  - time: 20250621120900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250621130900
    name: 粥水
    amount: 400
    unit: ml
  - time: 20250621140000
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250621155200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250621183000
    name: 汤水
    amount: 250
    unit: ml
  - time: 20250621190800
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250621201000
    name: 开水
    amount: 150
    unit: ml
med:
  - time: 20250621084200
    name: 楚牛牛磺酸
    amount: 1.0
    unit: g
  - time: 20250621100300
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20250621100300
    name: selenium
    amount: 200
    unit: μg
  - time: 20250621100300
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
