date: 20250814
food:
  - time: 20250814131000
    name: 李子
    amount: 50
    unit: g

  - time: 20250814131300
    name: 馒头2508a
    amount: 1
    unit: 个
  - time: 20250814131300
    name: 粉蒸肉2508a
    amount: 30.0
    unit: g
  - time: 20250814131300
    name: 南瓜
    amount: 75
    unit: g
  - time: 20250814131300
    name: 油菜
    amount: 100
    unit: g
  - time: 20250814131300
    name: 中盐绿色低钠湖盐
    amount: 0.5
    unit: g

  - time: 20250814132800
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250814132800
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250814132800
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250814134300
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250814134300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250814202700
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250814202700
    name: 域尚楼兰沙棘全果原浆
    amount: 25.0
    unit: g
  - time: 20250814202700
    name: 菊粉
    amount: 15.0
    unit: g
    
  - time: 20250814203800
    name: 油桃
    amount: 200
    unit: g

  - time: 20250814130000
    name: 扬农沁香米
    amount: 45.0
    unit: g
  - time: 20250814130000
    name: 紫米
    amount: 15.0
    unit: g
  - time: 20250814130000
    name: 鸡蛋
    amount: 45.0
    unit: g
  - time: 20250814130000
    name: 油菜
    amount: 150
    unit: g
  - time: 20250814130000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250814130000
    name: 油
    amount: 0.5
    unit: g
    
  - time: 20250814140000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250814140000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
    
  - time: 20250814202800
    name: 杏
    amount: 50
    unit: g
  - time: 20250814203000
    name: 李子
    amount: 60
    unit: g

  - time: 20250814204200
    name: 安尼斯意大利面
    amount: 50
    unit: g
  - time: 20250814204200
    name: 腌鸡腿肉2508a
    amount: 40
    unit: g
  - time: 20250814204200
    name: 胡萝卜
    amount: 60
    unit: g
  - time: 20250814204200
    name: 唯加南洋风味咖喱酱
    amount: 20
    unit: g
  - time: 20250814204200
    name: 油菜
    amount: 140
    unit: g
  - time: 20250814204200
    name: 油
    amount: 0.5
    unit: g

  - time: 20250814213000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250814213000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250814111200
    name: 开水
    amount: 200
    unit: ml
  - time: 20250814124700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250814134300
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250814144000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250814162300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250814140000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250814174700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250814193100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250814213000
    name: 可可奶
    amount: 80.5
    unit: ml
  - time: 20250814232900
    name: 开水
    amount: 175
    unit: ml
med:
  - time: 20250814134300
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250814144000
    name: selenium
    amount: 200
    unit: μg
  - time: 20250814144000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
