date: 20260121
food:
  - time: 20260121031500
    name: 桔柚
    amount: 90.0
    unit: g

  - time: 20260121031700
    name: 萝卜糕2601a
    amount: 200
    unit: g
  - time: 20260121031700
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20260121031700
    name: 南瓜
    amount: 120
    unit: g
  - time: 20260121031700
    name: 红菜苔
    amount: 120
    unit: g
  - time: 20260121031700
    name: 十三村原味腐乳
    amount: 10
    unit: g

  - time: 20260121033800
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260121033800
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260121033800
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260121034900
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260121034900
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260121101500
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20260121101500
    name: 疆二姐有机沙棘原浆
    amount: 30.0
    unit: g
  - time: 20260121101500
    name: 百香果
    amount: 40
    unit: g
  - time: 20260121101500
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20260121101600
    name: 苹果
    amount: 165
    unit: g

  - time: 20260121102100
    name: 大米
    amount: 60.0
    unit: g
  - time: 20260121102100
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20260121102100
    name: 红豆
    amount: 10.0
    unit: g
  - time: 20260121102100
    name: 卤兔腿2601b
    amount: 75.0
    unit: g
  - time: 20260121102100
    name: 杏鲍菇
    amount: 100
    unit: g
  - time: 20260121102100
    name: 油菜
    amount: 240
    unit: g
  - time: 20260121102100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260121102100
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260121105000
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260121105000
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g
  - time: 20260121105000
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g
water:
  - time: 20260121020000
    name: 开水
    amount: 200
    unit: ml
  - time: 20260121030400
    name: 开水
    amount: 250
    unit: ml
  - time: 20260121034900
    name: 咖啡
    amount: 101.0
    unit: ml
  - time: 20260121041500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260121053400
    name: 开水
    amount: 250
    unit: ml
  - time: 20260121073800
    name: 开水
    amount: 250
    unit: ml
  - time: 20260121081500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260121084800
    name: 开水
    amount: 250
    unit: ml
  - time: 20260121105000
    name: 咖啡
    amount: 101.0
    unit: ml
  - time: 20260121105600
    name: 开水
    amount: 150
    unit: ml
med:
  - time: 20260121034900
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260121041500
    name: selenium
    amount: 200
    unit: μg
  - time: 20260121041500
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
