date: 20260131
food:
  - time: 20260131060600
    name: 桔柚
    amount: 90
    unit: g
  - time: 20260131060600
    name: 释迦果
    amount: 150
    unit: g

  - time: 20260131073500
    name: 苏贝尔新疆拉条子挂面
    amount: 120
    unit: g
  - time: 20260131073500
    name: 客道爽脆腰花
    amount: 230
    unit: g
  - time: 20260131073500
    name: 小鹰大油方
    amount: 40
    unit: g
  - time: 20260131073500
    name: 西洋菜
    amount: 60
    unit: g
  - time: 20260131073500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260131073500
    name: 味精
    amount: 0.5
    unit: g

  - time: 20260131063900
    name: 黄吉利苕丝糖
    amount: 30
    unit: g
  - time: 20260131063900
    name: 新疆手工切糕
    amount: 30.0
    unit: g
  - time: 20260131063900
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260131063900
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260131063900
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260131073500
    name: 河套纯牛奶粉
    amount: 25.0
    unit: g
  - time: 20260131073500
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260131124900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20260131124900
    name: 戈壁密码有机沙棘原浆
    amount: 30
    unit: g
  - time: 20260131124900
    name: 百香果
    amount: 70
    unit: g
  - time: 20260131124900
    name: 菊粉
    amount: 5.0
    unit: g
  - time: 20260131124900
    name: 维生素C
    amount: 1.0
    unit: g
  - time: 20260131124900
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20260131125200
    name: 猕猴桃
    amount: 65
    unit: g

  - time: 20260131125800
    name: 一品寒香大米
    amount: 70
    unit: g
  - time: 20260131125800
    name: 高粱米
    amount: 10
    unit: g
  - time: 20260131125800
    name: 红豆
    amount: 10
    unit: g
  - time: 20260131125800
    name: 腌鸡腿肉2601a
    amount: 130
    unit: g
  - time: 20260131125800
    name: 红薯叶
    amount: 250
    unit: g
  - time: 20260131125800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260131125800
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260131140200
    name: 河套纯牛奶粉
    amount: 25.0
    unit: g
  - time: 20260131140200
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g
water:
  - time: 20260131043100
    name: 开水
    amount: 200
    unit: ml
  - time: 20260131053000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260131073500
    name: 汤水
    amount: 500.0
    unit: ml
  - time: 20260131073500
    name: 咖啡
    amount: 100.0
    unit: ml
  - time: 20260131073500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260131085500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260131094100
    name: 开水
    amount: 250
    unit: ml
  - time: 20260131105700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260131125800
    name: 汤水
    amount: 500
    unit: ml
  - time: 20260131140200
    name: 咖啡
    amount: 101.0
    unit: ml
  - time: 20260131183000
    name: 开水
    amount: 250
    unit: ml
med:
  - time: 20260131073500
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260131073500
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20260131073500
    name: selenium
    amount: 200
    unit: μg
  - time: 20260131073500
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
