date: 20250613
food:
  - time: 20250613070700
    name: 人参果
    amount: 120
    unit: g  
 
  - time: 20250613071400
    name: 馒头2506b
    amount: 1
    unit: 个
  - time: 20250613071400
    name: 南瓜
    amount: 50
    unit: g
  - time: 20250613190100
    name: 卤牛肚2506a
    amount: 50
    unit: g
  - time: 20250613071400
    name: 秋葵
    amount: 120
    unit: g
  - time: 20250613071400
    name: 枸杞
    amount: 3.0
    unit: g
  - time: 20250613071400
    name: 油莎豆
    amount: 5.0
    unit: g
  - time: 20250613071400
    name: 姜
    amount: 5.0
    unit: g  
  
  - time: 20250613073400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250613073400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250613073400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g  
  
  - time: 20250613074000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250613074000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g  
  
  - time: 20250613115900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250613115900
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250613115900
    name: 菊粉
    amount: 6.0
    unit: g
  
  - time: 20250613120100
    name: 李子
    amount: 135
    unit: g
   
  - time: 20250613120700
    name: 扬农沁香米
    amount: 60.0
    unit: g
  - time: 20250613120700
    name: 黑青稞
    amount: 20.0
    unit: g
  - time: 20250613120700
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20250613120700
    name: 烟熏腊肉
    amount: 30
    unit: g
  - time: 20250613120700
    name: 锦悦和五城茶干
    amount: 20
    unit: g
  - time: 20250613120700
    name: 油菜
    amount: 220
    unit: g
  
  - time: 20250613122000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250613122000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g  
  
  - time: 20250613182200
    name: 荔枝
    amount: 60
    unit: g
  
  - time: 20250613182500
    name: 土豆
    amount: 150
    unit: g
  - time: 20250613182500
    name: 鸡蛋
    amount: 48
    unit: g
  - time: 20250613182500
    name: 苦菊
    amount: 120
    unit: g
  - time: 20250613182500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250613182500
    name: 油
    amount: 0.5
    unit: g
  
  - time: 20250613184400
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250613184400
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250613060800
    name: 开水
    amount: 200
    unit: ml
  - time: 20250613065700
    name: 开水
    amount: 250
    unit: ml  
  - time: 20250613074000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250613078300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250613093100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250613102600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250613122000
    name: 咖啡
    amount: 80.0
    unit: ml    
  - time: 20250613140500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250613161200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250613184400
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250613190000
    name: 开水
    amount: 100
    unit: ml
med:
  - time: 20250613074000
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250613078300
    name: selenium
    amount: 200
    unit: μg
  - time: 20250613078300
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
