date: 20250921
food:
  - time: 20250921161100
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250921161100
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20250921161100
    name: 百香果
    amount: 40
    unit: g
  - time: 20250921161100
    name: 菊粉
    amount: 10
    unit: g

  - time: 20250921161300
    name: 猕猴桃
    amount: 80
    unit: g

  - time: 20250921161500
    name: 馒头2509a
    amount: 1
    unit: 个
  - time: 20250921161500
    name: 淮河红烧扣肉罐头
    amount: 100
    unit: g
  - time: 20250921161500
    name: 南瓜
    amount: 80
    unit: g
  - time: 20250921161500
    name: 西兰花
    amount: 90
    unit: g

  - time: 20250921162900
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250921162900
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250921162900
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250921164000
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250921164000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250921225500
    name: 京白梨
    amount: 225
    unit: g

  - time: 20250921225800
    name: 扬农沁香米
    amount: 60.0
    unit: g
  - time: 20250921225800
    name: 紫米
    amount: 20.0
    unit: g
  - time: 20250921225800
    name: 泉嫁艳青麦仁
    amount: 50.0
    unit: g
  - time: 20250921225800
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250921225800
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20250921225800
    name: 烟熏腊肉
    amount: 49.5
    unit: g
  - time: 20250921225800
    name: 快菜
    amount: 150
    unit: g
  - time: 20250921225800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250921225800
    name: 油
    amount: 0.5
    unit: g

  - time: 20250921235700
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250921235700
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250921130900
    name: 开水
    amount: 200
    unit: ml
  - time: 20250921155500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250921164000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250921173800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250921184800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250921201000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250921210500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250921225800
    name: 汤水
    amount: 500
    unit: ml
  - time: 20250921235700
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250921235900
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250921145000
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250921173800
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20250921173800
    name: selenium
    amount: 200
    unit: μg
  - time: 20250921173800
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
