date: 20250622
food:
  - time: 20250622080300
    name: 人参果
    amount: 130
    unit: g

  - time: 20250622080700
    name: 益奇多燕麦片
    amount: 10
    unit: g
  - time: 20250622080700
    name: 绿豆
    amount: 20.0
    unit: g
  - time: 20250622080700
    name: 泉嫁艳青麦仁
    amount: 20.0
    unit: g
  - time: 20250622080700
    name: 海带
    amount: 5.0
    unit: g
  - time: 20250622080700
    name: 蜂蜜
    amount: 10.0
    unit: g
  - time: 20250622080700
    name: 南瓜
    amount: 43
    unit: g
  - time: 20250622190100
    name: 粉蒸肉2506a
    amount: 40
    unit: g
  - time: 20250622080700
    name: 秋葵
    amount: 160
    unit: g
  - time: 20250622080700
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g

  - time: 20250622082600
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250622082600
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250622082600
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250622084200
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250622084200
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250622130400
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250622130400
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250622130400
    name: 艾斯蔗菊粉
    amount: 5
    unit: g

  - time: 20250622130500
    name: 李子
    amount: 90
    unit: g

  - time: 20250622130900
    name: 福润东方有机小米
    amount: 30
    unit: g
  - time: 20250622130900
    name: 扬农沁香米
    amount: 30.0
    unit: g
  - time: 20250622130900
    name: 泉嫁艳青麦仁
    amount: 20.0
    unit: g
  - time: 20250622130900
    name: 腌鸡腿肉2504b
    amount: 50
    unit: g
  - time: 20250622130900
    name: 快菜
    amount: 220.0
    unit: g
  - time: 20250622130900
    name: 胡萝卜
    amount: 100
    unit: g
  - time: 20250622130900
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250622130900
    name: 油
    amount: 0.5
    unit: g
  
  - time: 20250622143000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250622143000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250622191600
    name: 橙
    amount: 115
    unit: g

  - time: 20250622191900
    name: 土豆
    amount: 130
    unit: g
  - time: 20250622191900
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250622191900
    name: 香油臭豆腐乳
    amount: 10.0
    unit: g
  - time: 20250622191900
    name: 油菜
    amount: 150
    unit: g
  - time: 20250622191900
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250622191900
    name: 油
    amount: 0.5
    unit: g

  - time: 20250622202000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250622202000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250622064900
    name: 开水
    amount: 200
    unit: ml
  - time: 20250622074800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250622080700
    name: 粥水
    amount: 300
    unit: ml
  - time: 20250622084200
    name: 咖啡
    amount: 82.0
    unit: ml
  - time: 20250622100300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250622111000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250622143000
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250622162000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250622191900
    name: 汤水
    amount: 350
    unit: ml
  - time: 20250622202000
    name: 可可奶
    amount: 80.5
    unit: ml
  - time: 20250622214500
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250622084200
    name: 楚牛牛磺酸
    amount: 1.0
    unit: g
  - time: 20250622100300
    name: selenium
    amount: 200
    unit: μg
  - time: 20250622100300
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
