date: 20251001
food:
  - time: 20251001135900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251001135900
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20251001135900
    name: 百香果
    amount: 40
    unit: g
  - time: 20251001135900
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 202510011400000
    name: 猕猴桃
    amount: 80
    unit: g

  - time: 20251001140300
    name: 安居尔新疆味道五仁老月饼
    amount: 80
    unit: g
  - time: 20251001140300
    name: 卤牛肉2509b
    amount: 40
    unit: g
  - time: 20251001140300
    name: 南瓜
    amount: 85
    unit: g
  - time: 20251001140300
    name: 秋葵
    amount: 120
    unit: g

  - time: 20251001142400
    name: 蛋挞2509a
    amount: 1
    unit: 个
  - time: 20251001142400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251001142400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251001142400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251001143600
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251001143600
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251001184000
    name: 京白梨
    amount: 220
    unit: g

  - time: 20251001184400
    name: 扬农沁香米
    amount: 50.0
    unit: g
  - time: 20251001184400
    name: 紫米
    amount: 20.0
    unit: g
  - time: 20251001184400
    name: 泉嫁艳青麦仁
    amount: 50.0
    unit: g
  - time: 20251001184400
    name: 泰森轻食鸡胸肉排
    amount: 120
    unit: g
  - time: 20251001184400
    name: 小白菜
    amount: 180
    unit: g
  - time: 20251001184400
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251001184400
    name: 油
    amount: 0.5
    unit: g

  - time: 20251001302500
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251001302500
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251001120200
    name: 开水
    amount: 200
    unit: ml
  - time: 20251001133900
    name: 开水
    amount: 250
    unit: ml
  - time: 20251001143600
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251001153800
    name: 开水
    amount: 250
    unit: ml
  - time: 20251001164100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251001173800
    name: 开水
    amount: 250
    unit: ml
  - time: 20251001184400
    name: 汤水
    amount: 500
    unit: ml
  - time: 20251001302500
    name: 可可奶
    amount: 80.5
    unit: ml
med:
  - time: 20251001143600
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251001153800
    name: selenium
    amount: 200
    unit: μg
  - time: 20251001153800
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
