date: 20250730
food:
  - time: 2025073009185000
    name: 油桃
    amount: 150
    unit: g

  - time: 20250730095400
    name: 馒头2507d
    amount: 1
    unit: 个
  - time: 20250730095400
    name: 粉蒸肉2507c
    amount: 70
    unit: g
  - time: 20250730095400
    name: 南瓜
    amount: 75
    unit: g
  - time: 20250730095400
    name: 芦笋
    amount: 145
    unit: g

  - time: 20250730101000
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250730101000
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250730101000
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250730102400
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250730102400
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250730143800
    name: 番茄酱
    amount: 30.0
    unit: g
  - time: 20250730143800
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250730143800
    name: 菊粉
    amount: 10.0
    unit: g

  - time: 20250730143800
    name: 李子
    amount: 160
    unit: g

  - time: 20250730144100
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20250730144100
    name: 黑胡椒风味芊芊鱼排
    amount: 70
    unit: g
  - time: 20250730144100
    name: 大葱
    amount: 20.0
    unit: g
  - time: 20250730144100
    name: 姜
    amount: 10.0
    unit: g
  - time: 20250730144100
    name: 胡萝卜
    amount: 84.5
    unit: g
  - time: 20250730144100
    name: 油菜
    amount: 160
    unit: g
  - time: 20250730144100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250730144100
    name: 油
    amount: 0.5
    unit: g

  - time: 20250730151600
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250730151600
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250730194000
    name: 菇娘
    amount: 100
    unit: g

  - time: 20250730194300
    name: 土豆
    amount: 250
    unit: g
  - time: 20250730194300
    name: 鸡蛋
    amount: 45.0
    unit: g
  - time: 20250730194300
    name: 油菜
    amount: 120
    unit: g
  - time: 20250730194300
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250730194300
    name: 油
    amount: 0.5
    unit: g

  - time: 20250730202500
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250730202500
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250730082600
    name: 开水
    amount: 200
    unit: ml
  - time: 20250730092900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250730102400
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250730112700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250730115000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250730151600
    name: 咖啡
    amount: 82.0
    unit: ml
  - time: 20250730162400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250730194300
    name: 汤水
    amount: 400
    unit: ml
  - time: 20250730202500
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250730215400
    name: 开水
    amount: 150
    unit: ml
med:
  - time: 20250730102400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250730112700
    name: selenium
    amount: 200
    unit: μg
  - time: 20250730112700
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
