date: 20250907
food:
  - time: 20250907151800
    name: 棘密西梅原浆
    amount: 50
    unit: g
  - time: 20250907151800
    name: 域尚楼兰沙棘全果原浆
    amount: 50.0
    unit: g
  - time: 20250907151800
    name: 菊粉
    amount: 12.0
    unit: g

  - time: 20250907152000
    name: 冬枣
    amount: 135
    unit: g
  - time: 20250907153400
    name: 咖喱鸡肉2508b
    amount: 150.0
    unit: g
  - time: 20250907153400
    name: 南瓜
    amount: 75.0
    unit: g
  - time: 20250907153400
    name: 西兰花
    amount: 13.0
    unit: g

  - time: 20250907155000
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250907155000
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250907155000
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250907161300
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250907161300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250907130000
    name: 白桃
    amount: 200
    unit: g

  - time: 20250907131000
    name: 扬农沁香米
    amount: 40
    unit: g
  - time: 20250907131000
    name: 紫米
    amount: 15
    unit: g
  - time: 20250907131000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250907131000
    name: 圆白菜
    amount: 150
    unit: g
  - time: 20250907131000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250907131000
    name: 油
    amount: 0.5
    unit: g

  - time: 20250907131300
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250907131300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
    
  - time: 20250907222400
    name: 梨
    amount: 168.0
    unit: g

  - time: 20250907222700
    name: 安尼斯意大利面
    amount: 50
    unit: g
  - time: 20250907222700
    name: 猪舌
    amount: 45
    unit: g
  - time: 20250907222700
    name: 唯加南洋风味咖喱酱
    amount: 20.0
    unit: g
  - time: 20250907222700
    name: 圆白菜
    amount: 162.5
    unit: g
  - time: 20250907222700
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250907222700
    name: 油
    amount: 0.5
    unit: g

  - time: 20250907225500
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250907225500
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250907132100
    name: 开水
    amount: 200
    unit: ml
  - time: 20250907144800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250907161300
    name: 咖啡
    amount: 80
    unit: ml
  - time: 20250907165500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250907181200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250907131300
    name: 咖啡
    amount: 80
    unit: ml
  - time: 20250907193600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250907225500
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250907233700
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250907161300
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250907165500
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20250907165500
    name: selenium
    amount: 200
    unit: μg
  - time: 20250907165500
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
