date: 20251005
food:
  - time: 20251005121600
    name: 番石榴
    amount: 150
    unit: g

  - time: 20251005090000
    name: 馒头2510a
    amount: 1
    unit: 个
  - time: 20251005090000
    name: 卤猪舌2510a
    amount: 45
    unit: g
  - time: 20251005090000
    name: 南瓜
    amount: 60.0
    unit: g
  - time: 20251005090000
    name: 秋葵
    amount: 125
    unit: g

  - time: 20251005091200
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251005091200
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251005091200
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251005092300
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251005092300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251005121400
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251005121400
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20251005121400
    name: 菊粉
    amount: 13.0
    unit: g

  - time: 20251005085800
    name: 猕猴桃
    amount: 85
    unit: g

    
  - time: 20251005121600
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20251005121600
    name: 紫米
    amount: 15.0
    unit: g
  - time: 20251005121600
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20251005121600
    name: 泰森轻食鸡胸肉排
    amount: 40
    unit: g
  - time: 20251005121600
    name: 三文鱼
    amount: 20
    unit: g
    log: 不预热、上下火、中层、200°C+20分钟
  - time: 20251005121600
    name: 大白菜
    amount: 250
    unit: g
  - time: 20251005121600
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20251005121600
    name: 油
    amount: 0.5
    unit: g

  - time: 20251005124400
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251005124400
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251005174600
    name: 京白梨
    amount: 150
    unit: g
  - time: 20251005174800
    name: 香蕉
    amount: 0
    unit: g

  - time: 20251005175300
    name: 红薯
    amount: 50
    unit: g
  - time: 20251005175300
    name: 山药
    amount: 50
    unit: g
  - time: 20251005175300
    name: 松花鸭皮蛋
    amount: 60
    unit: g
  - time: 20251005175300
    name: 娃娃菜
    amount: 150
    unit: g
  - time: 20251005175300
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251005175300
    name: 油
    amount: 0.5
    unit: g

  - time: 20251005180900
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251005180900
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251005074400
    name: 开水
    amount: 200
    unit: ml
  - time: 20251005084100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251005092300
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251005095200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251005111400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251005124400
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251005143400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251005162100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251005175300
    name: 汤水
    amount: 400
    unit: ml
  - time: 20251005180900
    name: 可可奶
    amount: 81.5
    unit: ml
  - time: 20251005184000
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20251005092300
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251005095200
    name: selenium
    amount: 200
    unit: μg
  - time: 20251005095200
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
