date: 20260109
food:
  - time: 20260109040800
    name: 番石榴
    amount: 150
    unit: g

  - time: 20260109041100
    name: 年糕2601a
    amount: 150
    unit: g
  - time: 20260109041100
    name: 南瓜
    amount: 114.0
    unit: g
  - time: 20260109041100
    name: 象大厨经典卤水老豆腐
    amount: 50
    unit: g
  - time: 20260109041100
    name: 粉蒸肉2601a
    amount: 100
    unit: g
  - time: 20260109041100
    name: 红菜苔
    amount: 147.0
    unit: g

  - time: 20260109042400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260109042400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260109042400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260109043700
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20260109043700
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20260109092500
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20260109092500
    name: 疆二姐有机沙棘原浆
    amount: 0
    unit: g
  - time: 20260109092500
    name: 百香果
    amount: 20
    unit: g
  - time: 20260109092500
    name: 菊粉
    amount: 7.0
    unit: g
  - time: 20260109092500
    name: 维生素C
    amount: 2.0
    unit: g

  - time: 20260109115900
    name: 猕猴桃
    amount: 85
    unit: g
  - time: 20260109120300
    name: 金桔
    amount: 150
    unit: g

  - time: 20260109121000
    name: 馒头2601a
    amount: 1
    unit: 个
  - time: 20260109121000
    name: 娃娃鱼肉
    amount: 100
    unit: g
  - time: 20260109121000
    name: 楚郡味豆瓣酱
    amount: 10
    unit: g
  - time: 20260109121000
    name: 油菜
    amount: 250
    unit: g
  - time: 20260109121000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260109121000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260109131900
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20260109131900
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
  - time: 20260109131900
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g
f:
  - time: 20260109220000
    name: 土豆
    amount: 150
    unit: g
  - time: 20260109220000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20260109220000
    name: 油菜
    amount: 120
    unit: g
  - time: 20260109220000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260109220000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260109055000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20260109055000
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260109025200
    name: 开水
    amount: 200
    unit: ml
  - time: 20260109035300
    name: 开水
    amount: 250
    unit: ml
  - time: 20260109043700
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20260109045400
    name: 开水
    amount: 250
    unit: ml
  - time: 20260109115700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260109131700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260109144100
    name: 开水
    amount: 250
    unit: ml
  - time: 20260109131900
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20260109144400
    name: 开水
    amount: 225
    unit: ml
w:
  - time: 20260109161200
    name: 开水
    amount: 100
    unit: ml
  - time: 20260109055000
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20260109202800
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20260109043700
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260109045400
    name: selenium
    amount: 200
    unit: μg
  - time: 20260109045400
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |