date: 20260208
food:
  - time: 202602080613000
    name: 番石榴
    amount: 150
    unit: g
  - time: 202602080613000
    name: 香蕉
    amount: 100
    unit: g

  - time: 20260208061600
    name: 萝卜糕2602a
    amount: 220
    unit: g
  - time: 20260208061600
    name: 山药
    amount: 80
    unit: g
  - time: 20260208061600
    name: 南瓜
    amount: 50
    unit: g
  - time: 20260208061600
    name: 红菜苔
    amount: 140
    unit: g
  - time: 20260208061600
    name: 十三村原味腐乳
    amount: 7.5
    unit: g

  - time: 20260208062900
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260208062900
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260208062900
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260208063500
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260208063500
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260208115500
    name: 番茄酱
    amount: 20
    unit: g
  - time: 20260208115500
    name: 戈壁密码有机沙棘原浆
    amount: 20
    unit: g
  - time: 20260208115500
    name: 菊粉
    amount: 12.0
    unit: g

  - time: 20260208125600
    name: 猕猴桃
    amount: 60
    unit: g
  - time: 20260208115700
    name: 桔柚
    amount: 95.0
    unit: g

  - time: 20260208120000
    name: 一品寒香大米
    amount: 65
    unit: g
  - time: 20260208120000
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20260208120000
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20260208120000
    name: 腌鸡腿肉2602a
    amount: 130
    unit: g
    log:
      - 不预热、上中层、上下火、180°C+15分钟
      - 翻面、190°C+5分钟。
  - time: 20260208120000
    name: 黄心菜
    amount: 238.0
    unit: g
  - time: 20260208120000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260208120000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260208123100
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260208123100
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260208050400
    name: 开水
    amount: 200
    unit: ml
  - time: 20260208060000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260208063500
    name: 咖啡
    amount: 100.5
    unit: ml
  - time: 20260208070800
    name: 开水
    amount: 250
    unit: ml
  - time: 20260208085000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260208092800
    name: 开水
    amount: 250
    unit: ml
  - time: 20260208104500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260208123100
    name: 可可奶
    amount: 100.0
    unit: ml
  - time: 20260208145200
    name: 开水
    amount: 250
    unit: ml
med:
  - time: 20260208063500
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260208070800
    name: selenium
    amount: 200
    unit: μg
  - time: 20260208070800
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
