date: 20251002
food:
  - time: 202510021000000
    name: 猕猴桃
    amount: 80.0
    unit: g

  - time: 20251002100400
    name: 馒头2509b
    amount: 1
    unit: 个
  - time: 20251002100400
    name: 卤牛肉2509b
    amount: 45
    unit: g
  - time: 20251002100400
    name: 南瓜
    amount: 65
    unit: g
  - time: 20251002100400
    name: 秋葵
    amount: 140
    unit: g

  - time: 20251002102400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251002102400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251002102400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251002104800
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251002104800
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251002095900
    name: 番茄酱
    amount: 30.0
    unit: g
  - time: 20251002095900
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20251002095900
    name: 百香果
    amount: 40
    unit: g
  - time: 20251002095900
    name: 菊粉
    amount: 13.0
    unit: g

  - time: 20251002120000
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20251002120000
    name: 紫米
    amount: 15.0
    unit: g
  - time: 20251002120000
    name: 泉嫁艳青麦仁
    amount: 30.0
    unit: g
  - time: 20251002120000
    name: 泰森轻食鸡胸肉排
    amount: 125
    unit: g
  - time: 20251002120000
    name: 娃娃菜
    amount: 180
    unit: g
  - time: 20251002120000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251002120000
    name: 油
    amount: 0.5
    unit: g

  - time: 20251002130000
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251002130000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251002181000
    name: 京白梨
    amount: 120
    unit: g

  - time: 20251002180000
    name: 阿拉里玉米面条
    amount: 50
    unit: g
  - time: 20251002180000
    name: 鸡蛋
    amount: 50
    unit: g
  - time: 20251002180000
    name: 大白菜
    amount: 100
    unit: g
  - time: 20251002180000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251002180000
    name: 油
    amount: 0.5
    unit: g

  - time: 20251002185000
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251002185000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251002083200
    name: 开水
    amount: 200
    unit: ml
  - time: 20251002094100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251002104800
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251002113400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251002123200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251002142600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251002130000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251002145200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251002155200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251002185000
    name: 可可奶
    amount: 60.0
    unit: ml
  - time: 20251002191400
    name: 开水
    amount: 150
    unit: ml
med:
  - time: 20251002104800
    name: 楚牛牛磺酸
    amount: 1.0
    unit: g
  - time: 20251002113400
    name: selenium
    amount: 200
    unit: μg
  - time: 20251002113400
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
