date: 20251115
food:
  - time: 20251115110300
    name: 梨
    amount: 85
    unit: g
  - time: 20251115110600
    name: 柿子
    amount: 30
    unit: g

  - time: 20251115110800
    name: 土豆
    amount: 150
    unit: g
  - time: 20251115110800
    name: 阿拉里玉米面条
    amount: 20
    unit: g
  - time: 20251115110800
    name: 粮农星厨老母鸡汤
    amount: 360.0
    unit: g
  - time: 20251115110800
    name: 南瓜
    amount: 70.0
    unit: g
  - time: 20251115110800
    name: 洋葱
    amount: 52.5
    unit: g
  - time: 20251115110800
    name: 胡萝卜
    amount: 50
    unit: g
  - time: 20251115110800
    name: 圆白菜
    amount: 50
    unit: g
  - time: 20251115110800
    name: 枸杞
    amount: 5.0
    unit: g
  - time: 20251115110800
    name: 西兰苔
    amount: 140
    unit: g
  - time: 20251115110800
    name: 王致和减盐玫瑰腐乳
    amount: 15.0
    unit: g

  - time: 20251115112500
    name: 如紫兰果仁月饼
    amount: 35.0
    unit: g
  - time: 20251115112500
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251115112500
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251115112500
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251115113400
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251115113400
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20251115181900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251115181900
    name: 东棘沙棘原浆
    amount: 30.0
    unit: g
  - time: 20251115181900
    name: 菊粉
    amount: 11.0
    unit: g
  - time: 20251115181900
    name: 臻妍益生菌冻干粉2509
    amount: 3
    unit: g

  - time: 20251115182000
    name: 苹果
    amount: 180
    unit: g

  - time: 20251115182300
    name: 红薯
    amount: 230
    unit: g
  - time: 20251115182300
    name: 杏鲍菇
    amount: 120
    unit: g
  - time: 20251115182300
    name: 东古叉烧酱
    amount: 20.0
    unit: g
  - time: 20251115182300
    name: 松板肉
    amount: 100
    unit: g
    log: 肉层比较厚，200°C+20分钟，180°C+10分钟。
  - time: 20251115182300
    name: 黄心菜
    amount: 260
    unit: g
  - time: 20251115182300
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20251115182300
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251115184500
    name: 麦陇香墨子酥
    amount: 0
    unit: g
  - time: 20251115185800
    name: 奶粉
    amount: 10.0
    unit: g
  - time: 20251115185800
    name: 伊利脱脂奶粉
    amount: 20.0
    unit: g
  - time: 20251115185800
    name: 兴科可可粉
    amount: 4.5
    unit: g
water:
  - time: 20251115093700
    name: 开水
    amount: 150
    unit: ml
  - time: 20251115104200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251115110800
    name: 汤水
    amount: 300
    unit: ml
  - time: 20251115113400
    name: 咖啡
    amount: 120.0
    unit: ml
  - time: 20251115124200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251115125500
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251115133500
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251115142800
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251115152000
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251115185800
    name: 可可奶
    amount: 120.5
    unit: ml
  - time: 20251115191300
    name: 开水
    amount: 100
    unit: ml
med:
  - time: 20251115113400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251115124200
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20251115124200
    name: selenium
    amount: 200
    unit: μg
  - time: 20251115124200
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
