date: 20260731
food:
  - time: 20260731204100
    name: 菇娘
    amount: 130
    unit: g
  - time: 20260731204100
    name: 李子
    amount: 125
    unit: g
    log: 青脆李

  - time: 20260731205100
    name: 小象高纤快熟燕麦片
    amount: 10.0
    unit: g
  - time: 20260731205100
    name: 干山药
    amount: 9.5
    unit: g
  - time: 20260731205100
    name: 银耳
    amount: 5.0
    unit: g
  - time: 20260731205100
    name: 莲子
    amount: 4.5
    unit: g
  - time: 20260731205100
    name: 薏米
    amount: 5.0
    unit: g
  - time: 20260731205100
    name: 干百合
    amount: 2.0
    unit: g
    log: 
      - 黄芪2.0g
      - 麦冬2.0g
  - time: 20260731205100
    name: 烤叉烧2607a
    amount: 40
    unit: g
  - time: 20260731205100
    name: 鸡蛋
    amount: 52.0
    unit: g
  - time: 20260731205100
    name: 南瓜
    amount: 120
    unit: g
    log: 贝栗美
  - time: 20260731205100
    name: 秋葵
    amount: 160
    unit: g
  - time: 20260731205100
    name: 十三村原味腐乳
    amount: 10
    unit: g

  - time: 20260731211500
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260731211500
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260731211500
    name: 桑葚干
    amount: 15.0
    unit: g

  - time: 20260731214500
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20260731214500
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260731043100
    name: 番茄酱
    amount: 25
    unit: g
  - time: 20260731043100
    name: 棘密沙棘原浆
    amount: 25.0
    unit: g
  - time: 20260731043100
    name: 菊粉
    amount: 12.0
    unit: g

  - time: 20260731043400
    name: 蜜桃
    amount: 193.0
    unit: g
    log: 鹰嘴桃

  - time: 20260731044000
    name: 光明谷锦崇明大米
    amount: 70.0
    unit: g
  - time: 20260731044000
    name: 紫米
    amount: 10.0
    unit: g
  - time: 20260731044000
    name: 三文鱼
    amount: 50
    unit: g
  - time: 20260731044000
    name: 红薯叶
    amount: 220
    unit: g
  - time: 20260731044000
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20260731044000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g


  - time: 20260731183000
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20260731183000
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260731184500
    name: 开水
    amount: 200
    unit: ml
  - time: 20260731200300
    name: 开水
    amount: 250
    unit: ml
  - time: 20260731205100
    name: 粥水
    amount: 500
    unit: ml
  - time: 20260731214500
    name: 咖啡
    amount: 120.0
    unit: ml
  - time: 20260731224000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260731000700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260731183000
    name: 可可奶
    amount: 120
    unit: ml
  - time: 20260731051800
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20260731214500
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260731224000
    name: selenium
    amount: 200
    unit: μg
  - time: 20260731224000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
