date: 20260218
food:
  - time: 20260218064700
    name: 释迦果
    amount: 150
    unit: g
  - time: 20260218064900
    name: 苹果
    amount: 125
    unit: g

  - time: 20260218065200
    name: 萝卜糕2602a
    amount: 180
    unit: g
  - time: 20260218065200
    name: 山药
    amount: 90
    unit: g
  - time: 20260218065200
    name: 南瓜
    amount: 40
    unit: g
  - time: 20260218065200
    name: 红菜苔
    amount: 150
    unit: g
  - time: 20260218065200
    name: 十三村原味腐乳
    amount: 8.0
    unit: g

  - time: 20260218070700
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260218070700
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260218070700
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260218071900
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260218071900
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260218150000
    name: 番茄酱
    amount: 25.0
    unit: g
  - time: 20260218150000
    name: 戈壁密码有机沙棘原浆
    amount: 25
    unit: g
  - time: 20260218150000
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20260218150200
    name: 安尼斯意大利面
    amount: 80
    unit: g
  - time: 20260218150200
    name: 鲟鱼
    amount: 100
    unit: g
  - time: 20260218150200
    name: 油菜
    amount: 230
    unit: g
  - time: 20260218150200
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260218150200
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260218160000
    name: 柿子
    amount: 240
    unit: g

  - time: 20260218160400
    name: 河套纯牛奶粉
    amount: 25.0
    unit: g
  - time: 20260218160400
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260218052300
    name: 开水
    amount: 200
    unit: ml
  - time: 20260218062800
    name: 开水
    amount: 250
    unit: ml
  - time: 20260218071900
    name: 咖啡
    amount: 102.0
    unit: ml
  - time: 20260218074000
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260218085700
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260218092200
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260218121900
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260218132200
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260218160400
    name: 可可奶
    amount: 100.5
    unit: ml
  - time: 20260218162500
    name: 红茶
    amount: 250
    unit: ml
med:
  - time: 20260218071900
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260218074000
    name: selenium
    amount: 200
    unit: μg
  - time: 20260218074000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
