date: 20250706
food:
  - time: 20250706084400
    name: 油桃
    amount: 107.0
    unit: g

  - time: 20250706084700
    name: 馒头2507a
    amount: 1
    unit: 个
  - time: 20250706084700
    name: 南瓜
    amount: 35
    unit: g
  - time: 20250706190100
    name: 卤牛肚2506b
    amount: 50
    unit: g
  - time: 20250706084700
    name: 芦笋
    amount: 150
    unit: g
  - time: 20250706084700
    name: 中盐绿色低钠湖盐
    amount: 0.5
    unit: g

  - time: 20250706090200
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250706090200
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250706090200
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250706091300
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250706091300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250706125900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250706125900
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250706125900
    name: 艾斯蔗菊粉
    amount: 10
    unit: g

  - time: 20250706130000
    name: 李子
    amount: 86.5
    unit: g
  - time: 20250706130100
    name: 杏
    amount: 70.0
    unit: g

  - time: 20250706130400
    name: 扬农沁香米
    amount: 50.0
    unit: g
  - time: 20250706130400
    name: 福润东方有机小米
    amount: 20.0
    unit: g
  - time: 20250706130400
    name: 泉嫁艳青麦仁
    amount: 50.0
    unit: g
  - time: 20250706130400
    name: 腌鸡腿肉2504b
    amount: 50.0
    unit: g
  - time: 20250706130400
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20250706130400
    name: 快菜
    amount: 180
    unit: g
  - time: 20250706130400
    name: 胡萝卜
    amount: 100
    unit: g
  - time: 20250706130400
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250706130400
    name: 油
    amount: 0.5
    unit: g

  - time: 20250706133500
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250706133500
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250706184700
    name: 圣女果
    amount: 177.0
    unit: g
    log:
      - 糖珀琥74.0g
      - 圣女果103.0g

  - time: 20250706185200
    name: 土豆
    amount: 150
    unit: g
  - time: 20250706185200
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250706185200
    name: 香油臭豆腐乳
    amount: 17.0
    unit: g
  - time: 20250706185200
    name: 油菜
    amount: 130
    unit: g
  - time: 20250706185200
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20250706185200
    name: 油
    amount: 0.5
    unit: g

  - time: 20250706191900
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250706191900
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250706073400
    name: 开水
    amount: 200
    unit: ml
  - time: 20250706082900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250706091300
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250706101400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250706104900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250706133500
    name: 咖啡
    amount: 83.5
    unit: ml
  - time: 20250706152200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250706170000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250706191900
    name: 可可奶
    amount: 80.5
    unit: ml
  - time: 20250706205200
    name: 开水
    amount: 125
    unit: ml
med:
  - time: 20250706091300
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250706101400
    name: selenium
    amount: 200
    unit: μg
  - time: 20250706101400
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
