date: 20250827
food:
  - time: 20250827134000
    name: 杏
    amount: 55
    unit: g
  - time: 20250827134000
    name: 葡萄
    amount: 150
    unit: g

  - time: 20250827134600
    name: 红薯
    amount: 250
    unit: g
  - time: 20250827134600
    name: 圣农原汁原味肉多多鸡块
    amount: 50
    unit: g
    log:
      - 实际是外卖炸鸡块。
  - time: 20250827134600
    name: 蜂蜜
    amount: 22.0
    unit: g
    log:
      - 实际是外卖的蜂蜜芥末蘸酱。
  - time: 20250827134600
    name: 南瓜
    amount: 70
    unit: g
  - time: 20250827134600
    name: 西兰花
    amount: 140
    unit: g

  - time: 20250827140100
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250827140100
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250827140100
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250827133000
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250827133000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250827190700
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250827190700
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250827190700
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20250827190800
    name: 油桃
    amount: 175
    unit: g

  - time: 20250827191200
    name: 馒头2508c
    amount: 1
    unit: 个
  - time: 20250827191200
    name: 淮河红烧扣肉罐头
    amount: 150
    unit: g
  - time: 20250827191200
    name: 小白菜
    amount: 100
    unit: g
  - time: 20250827191200
    name: 油菜
    amount: 100
    unit: g
  - time: 20250827191200
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250827191200
    name: 油
    amount: 0.5
    unit: g

  - time: 20250827202000
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250827202000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250827115900
    name: 开水
    amount: 200
    unit: ml
  - time: 20250827131900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250827133000
    name: 咖啡
    amount: 89.5
    unit: ml
  - time: 20250827153000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250827164500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250827182300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250827202000
    name: 可可奶
    amount: 89.5
    unit: ml
  - time: 20250827215100
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250827133000
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250827153000
    name: selenium
    amount: 200
    unit: μg
  - time: 20250827153000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
