date: 20260311
food:
  - time: 20260311121000
    name: 番石榴
    amount: 150
    unit: g
  - time: 20260311121200
    name: 柑橘
    amount: 105
    unit: g

  - time: 20260311121600
    name: 萝卜糕2602b
    amount: 180
    unit: g
  - time: 20260311121600
    name: 鸡蛋
    amount: 0
    unit: g
  - time: 20260311121600
    name: 兰小糯糯玉米
    amount: 120
    unit: g
  - time: 20260311121600
    name: 南瓜
    amount: 70
    unit: g
  - time: 20260311121600
    name: 芦笋
    amount: 70
    unit: g
  - time: 20260311121600
    name: 西兰苔
    amount: 90
    unit: g
  - time: 20260311121600
    name: 十三村原味腐乳
    amount: 8.0
    unit: g

  - time: 20260311131400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260311131400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260311131400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260311125100
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260311125100
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260311201800
    name: 番茄酱
    amount: 26.0
    unit: g
  - time: 20260311201800
    name: 药都拾遗有机沙棘全果原浆
    amount: 27.5
    unit: g
  - time: 20260311201800
    name: 菊粉
    amount: 4.0
    unit: g

  - time: 20260311201800
    name: 人参果
    amount: 190
    unit: g

  - time: 20260311202300
    name: 一品寒香大米
    amount: 45.0
    unit: g
  - time: 20260311202300
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20260311202300
    name: 红豆
    amount: 10.0
    unit: g
  - time: 20260311202300
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20260311202300
    name: 草鱼
    amount: 100
    unit: g
    log:
      - 撒1.5克低钠盐，
      - 不预热、上下火、上层、180°C+15分钟
      - 翻面、200°C+5分钟
  - time: 20260311202300
    name: 菜心
    amount: 220
    unit: g
  - time: 20260311202300
    name: 中盐绿色低钠湖盐
    amount: 2.5
    unit: g
  - time: 20260311202300
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260311205200
    name: 山悠农乡蒜香花生
    amount: 0
    unit: g
  - time: 20260311210000
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260311210000
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260311105200
    name: 开水
    amount: 200
    unit: ml
  - time: 20260311120200
    name: 开水
    amount: 250
    unit: ml
  - time: 20260311125100
    name: 咖啡
    amount: 101.5
    unit: ml
  - time: 20260311131400
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260311135000
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260311143400
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260311153700
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260311174000
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260311210000
    name: 可可奶
    amount: 100.0
    unit: ml
  - time: 20260311205000
    name: 红茶
    amount: 300
    unit: ml
med:
  - time: 20260311125100
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260311131400
    name: selenium
    amount: 200
    unit: μg
  - time: 20260311131400
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
