date: 20251104
food:
  - time: 20251104114700
    name: 猕猴桃
    amount: 60
    unit: g
  - time: 20251104114700
    name: 番石榴
    amount: 150
    unit: g

  - time: 20251104115200
    name: 馒头2510c
    amount: 1
    unit: 个
  - time: 20251104115200
    name: 炖排骨2511a
    amount: 50
    unit: g
  - time: 20251104115200
    name: 南瓜
    amount: 90
    unit: g
  - time: 20251104115200
    name: 秋葵
    amount: 130
    unit: g

  - time: 20251104120800
    name: 如紫兰果仁月饼
    amount: 33
    unit: g
  - time: 20251104120800
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251104120800
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251104120800
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251104121800
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251104121800
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20251104180800
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251104180800
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20251104180800
    name: 菊粉
    amount: 5.0
    unit: g
  - time: 20251104180800
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20251104181100
    name: 梨
    amount: 75.0
    unit: g
  - time: 20251104181100
    name: 猕猴桃
    amount: 60
    unit: g

  - time: 20251104181400
    name: 扬农沁香米
    amount: 45.0
    unit: g
  - time: 20251104181400
    name: 紫米
    amount: 15.0
    unit: g
  - time: 20251104181400
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20251104181400
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20251104181400
    name: 大成奥尔良味香煎鸡扒
    amount: 71.0
    unit: g
  - time: 20251104181400
    name: 油菜
    amount: 230
    unit: g
  - time: 20251104181400
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251104181400
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251104185000
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251104185000
    name: 兴科可可粉
    amount: 4.5
    unit: g
water:
  - time: 20251104103000
    name: 开水
    amount: 200
    unit: ml
  - time: 20251104113400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251104121800
    name: 咖啡
    amount: 123.0
    unit: ml
  - time: 20251104125700
    name: 开水
    amount: 250
    unit: ml
  - time: 20251104135000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251104150400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251104162100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251104183700
    name: 汤水
    amount: 250
    unit: ml
  - time: 20251104185000
    name: 可可奶
    amount: 120.0
    unit: ml
  - time: 20251104194600
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20251104121800
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251104125700
    name: selenium
    amount: 200
    unit: μg
  - time: 20251104125700
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
