date: 20250807
food:
  - time: 20250807090500
    name: 油桃
    amount: 120
    unit: g

  - time: 20250807134500
    name: 土豆
    amount: 200
    unit: g
  - time: 20250807134500
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250807134500
    name: 黄山原味毛豆腐乳
    amount: 12
    unit: g
  - time: 20250807134500
    name: 油菜
    amount: 120
    unit: g
  - time: 20250807134500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250807134500
    name: 油
    amount: 0.5
    unit: g

  - time: 20250807092600
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250807092600
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250807092600
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250807095000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250807095000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250807133800
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250807133800
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250807133800
    name: 菊粉
    amount: 11
    unit: g

  - time: 20250807134000
    name: 菇娘
    amount: 100
    unit: g

  - time: 20250807134500
    name: 扬农沁香米
    amount: 35.0
    unit: g
  - time: 20250807134500
    name: 紫米
    amount: 20.0
    unit: g
  - time: 20250807134500
    name: 卤牛肚2508a
    amount: 40
    unit: g
  - time: 20250807134500
    name: 快菜
    amount: 220.0
    unit: g
  - time: 20250807134500
    name: 胡萝卜
    amount: 75
    unit: g
  - time: 20250807134500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250807134500
    name: 油
    amount: 0.5
    unit: g

  - time: 20250807140400
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250807140400
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250807194800
    name: 李子
    amount: 138.5
    unit: g

  - time: 20250807195200
    name: 馒头2508a
    amount: 1
    unit: 个
  - time: 20250807195200
    name: 粉蒸肉2508a
    amount: 40.0
    unit: g
  - time: 20250807195200
    name: 南瓜
    amount: 91.0
    unit: g
  - time: 20250807195200
    name: 西兰花
    amount: 150
    unit: g

  - time: 20250807200800
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250807200800
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250807074900
    name: 开水
    amount: 200
    unit: ml
  - time: 20250807084800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250807095000
    name: 咖啡
    amount: 91.0
    unit: ml
  - time: 20250807102100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250807114700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250807110800
    name: 粥水
    amount: 250
    unit: ml
  - time: 20250807140400
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20250807160100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250807200800
    name: 可可奶
    amount: 80.5
    unit: ml
  - time: 20250807203800
    name: 开水
    amount: 250
    unit: ml
med:
  - time: 20250807095000
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250807102100
    name: selenium
    amount: 200
    unit: μg
  - time: 20250807102100
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
