date: 20251027
food:
  - time: 20251027103700
    name: 猕猴桃
    amount: 70
    unit: g

  - time: 20251027103800
    name: 红薯
    amount: 101.0
    unit: g
  - time: 20251027103800
    name: 山药豆
    amount: 65
    unit: g
  - time: 20251027103800
    name: 炖排骨2510d
    amount: 50
    unit: g
  - time: 20251027103800
    name: 秋葵
    amount: 135
    unit: g
  - time: 20251027103800
    name: 南瓜
    amount: 105
    unit: g

  - time: 20251027105400
    name: 如紫兰果仁月饼
    amount: 34.0
    unit: g
  - time: 20251027105400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251027105400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251027105400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251027110800
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251027110800
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20251027194600
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251027194600
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20251027194600
    name: 菊粉
    amount: 12.0
    unit: g
  - time: 20251027194600
    name: 百香果
    amount: 50
    unit: g
  - time: 20251027194600
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20251027195300
    name: 山楂
    amount: 75
    unit: g

  - time: 20251027200400
    name: 全麦面包2510a
    amount: 80
    unit: g
  - time: 20251027200400
    name: 腌鸡膝软骨2510a
    amount: 100
    unit: g
  - time: 20251027200400
    name: 小白菜
    amount: 250.0
    unit: g
  - time: 20251027200400
    name: 象大厨北豆腐
    amount: 100
    unit: g
  - time: 20251027200400
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20251027200400
    name: 味精
    amount: 1.0
    unit: g
  - time: 20251027200400
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251027201600
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251027201600
    name: 兴科可可粉
    amount: 4.5
    unit: g
water:
  - time: 20251027100600
    name: 开水
    amount: 150
    unit: ml

  - time: 20251027102200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251027103800
    name: 汤水
    amount: 500
    unit: ml
  - time: 20251027110800
    name: 咖啡
    amount: 120.0
    unit: ml
  - time: 20251027113600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251027134100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251027141600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251027150300
    name: 开水
    amount: 250
    unit: ml
  - time: 20251027162000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251027201600
    name: 可可奶
    amount: 120.0
    unit: ml
  - time: 20251027204300
    name: 开水
    amount: 120
    unit: ml
med:
  - time: 20251027110800
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251027113600
    name: selenium
    amount: 200
    unit: μg
  - time: 20251027113600
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
