date: 20251020
food:
  - time: 20251020110800
    name: 猕猴桃
    amount: 65
    unit: g

  - time: 20251020111100
    name: 馒头2510b
    amount: 1
    unit: 个
  - time: 20251020110500
    name: 南瓜
    amount: 100
    unit: g
  - time: 20251020110500
    name: 炖排骨2510c
    amount: 50
    unit: g
  - time: 20251020110500
    name: 秋葵
    amount: 125
    unit: g

  - time: 20251020112600
    name: 安居尔新疆味道五仁老月饼
    amount: 0
    unit: g
  - time: 20251020112600
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251020112600
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251020112600
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251020113700
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251020113700
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251020183100
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251020183100
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20251020183100
    name: 菊粉
    amount: 5.0
    unit: g
  - time: 20251020183100
    name: 百香果
    amount: 45
    unit: g
  - time: 20251020183100
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20251020123000
    name: 扬农沁香米
    amount: 40
    unit: g
  - time: 20251020123000
    name: 紫米
    amount: 15
    unit: g
  - time: 20251020123000
    name: 绿豆
    amount: 10
    unit: g
  - time: 20251020123000
    name: 腌鸡膝软骨2510a
    amount: 80
    unit: g
  - time: 20251020123000
    name: 菠菜
    amount: 200
    unit: g
  - time: 20251020123000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251020123000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251020130000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251020130000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251020183300
    name: 油桃
    amount: 225
    unit: g

  - time: 20251020183700
    name: 红薯
    amount: 130
    unit: g
  - time: 20251020183700
    name: 山药豆
    amount: 40
    unit: g
  - time: 20251020183700
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20251020183700
    name: 油菜
    amount: 150
    unit: g
  - time: 20251020183700
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251020183700
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251020190500
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251020190500
    name: 可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251020094100
    name: 开水
    amount: 200
    unit: ml
  - time: 20251020105000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251020113700
    name: 咖啡
    amount: 121.0
    unit: ml
  - time: 20251020120600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251020135700
    name: 开水
    amount: 250
    unit: ml
  - time: 20251020142400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251020153100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251020160700
    name: 开水
    amount: 250
    unit: ml
  - time: 20251020190500
    name: 可可奶
    amount: 120.0
    unit: ml
  - time: 20251020200800
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20251020113700
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251020120600
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20251020120600
    name: selenium
    amount: 200
    unit: μg
  - time: 20251020120600
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
