date: 20250912
food:
  - time: 20250912132800
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250912132800
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20250912132800
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20250912133200
    name: 冬枣
    amount: 140
    unit: g
  - time: 20250912134700
    name: 咖喱鸡肉2509a
    amount: 130.0
    unit: g
  - time: 20250912134700
    name: 南瓜
    amount: 85
    unit: g
  - time: 20250912134700
    name: 西兰苔
    amount: 140
    unit: g

  - time: 20250912135700
    name: 伯香村蛋黄月饼
    amount: 0
    unit: g
  - time: 20250912140000
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250912140000
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250912140000
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250912140900
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250912140900
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250912120000
    name: 猕猴桃
    amount: 90
    unit: g

  - time: 20250912122000
    name: 扬农沁香米
    amount: 40
    unit: g
  - time: 20250912122000
    name: 紫米
    amount: 15
    unit: g
  - time: 20250912122000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250912122000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250912122000
    name: 油
    amount: 0.5
    unit: g

  - time: 20250912133000
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250912133000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250912173000
    name: 梨
    amount: 220
    unit: g
    
  - time: 20250912191000
    name: 馒头2509a
    amount: 1
    unit: 个
  - time: 20250912191000
    name: 卤猪舌2509a
    amount: 35.0
    unit: g
  - time: 20250912191000
    name: 圆白菜
    amount: 146.5
    unit: g
  - time: 20250912191000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g

  - time: 20250912200000
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250912200000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250912114800
    name: 开水
    amount: 200
    unit: ml
  - time: 20250912130300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250912140900
    name: 咖啡
    amount: 88.0
    unit: ml
  - time: 20250912143800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250912155200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250912164600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250912191000
    name: 汤水
    amount: 500
    unit: ml
  - time: 20250912200000
    name: 可可奶
    amount: 88.5
    unit: ml
  - time: 20250912221900
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250912140900
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250912143800
    name: selenium
    amount: 200
    unit: μg
  - time: 20250912143800
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
