date: 20250828
food:
  - time: 20250828130000
    name: 杏
    amount: 55
    unit: g

  - time: 20250828130200
    name: 葡萄
    amount: 150
    unit: g

  - time: 20250828130700
    name: 馒头2508c
    amount: 1
    unit: 个
  - time: 20250828130700
    name: 淮河红烧扣肉罐头
    amount: 150
    unit: g
  - time: 20250828130700
    name: 南瓜
    amount: 70
    unit: g
  - time: 20250828130700
    name: 西兰花
    amount: 130
    unit: g

  - time: 20250828132400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250828132400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250828132400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250828133800
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250828133800
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250828220800
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250828220800
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250828220800
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20250828220900
    name: 白桃
    amount: 225
    unit: g

  - time: 20250828221300
    name: 红薯
    amount: 250
    unit: g
  - time: 20250828221300
    name: 粉蒸肉2508c
    amount: 50
    unit: g
  - time: 20250828221300
    name: 小白菜
    amount: 150
    unit: g
  - time: 20250828221300
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250828221300
    name: 油
    amount: 0.5
    unit: g

  - time: 20250828224700
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250828224700
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250828104600
    name: 开水
    amount: 200
    unit: ml
  - time: 20250828123900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250828133800
    name: 咖啡
    amount: 81.5
    unit: ml
  - time: 20250828153000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250828143200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250828154200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250828184400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250828201400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250828221300
    name: 汤水
    amount: 250
    unit: ml
  - time: 20250828224700
    name: 可可奶
    amount: 81.0
    unit: ml
  - time: 20250828230800
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250828133800
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250828153000
    name: selenium
    amount: 200
    unit: μg
  - time: 20250828153000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
