date: 20250904
food:
  - time: 20250904105200
    name: 番茄酱
    amount: 15
    unit: g
  - time: 20250904105200
    name: 棘密西梅原浆
    amount: 50
    unit: g
  - time: 20250904105200
    name: 菊粉
    amount: 4
    unit: g

  - time: 20250904105400
    name: 梨
    amount: 250
    unit: g

  - time: 20250904185300
    name: 冬枣
    amount: 150
    unit: g
  - time: 20250904185300
    name: 咖喱鸡肉2508b
    amount: 180
    unit: g
  - time: 20250904185300
    name: 塞北老马红烧牛肉罐头
    amount: 40
    unit: g
  - time: 20250904185300
    name: 南瓜
    amount: 75
    unit: g
  - time: 20250904185300
    name: 西兰花
    amount: 130
    unit: g

  - time: 20250904111700
    name: 家利原味烧饼
    amount: 30
    unit: g
  - time: 20250904111700
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250904111700
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250904111700
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250904113000
    name: 我的童年纯牛奶粉
    amount: 30.0
    unit: g
  - time: 20250904113000
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20250904184500
    name: 番茄酱
    amount: 15
    unit: g
  - time: 20250904184500
    name: 域尚楼兰沙棘全果原浆
    amount: 30
    unit: g
  - time: 20250904184500
    name: 菊粉
    amount: 4
    unit: g

  - time: 20250904184900
    name: 白桃
    amount: 200
    unit: g

  - time: 20250904185300
    name: 红薯
    amount: 250
    unit: g
  - time: 20250904185300
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250904185300
    name: 小白菜
    amount: 150
    unit: g
  - time: 20250904185300
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250904185300
    name: 油
    amount: 0.5
    unit: g

  - time: 20250904192500
    name: 我的童年纯牛奶粉
    amount: 30.0
    unit: g
  - time: 20250904192500
    name: 天然可可粉
    amount: 4.5
    unit: g
water:
  - time: 20250904093100
    name: 开水
    amount: 200
    unit: ml
  - time: 20250904102800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250904113000
    name: 咖啡
    amount: 120.5
    unit: ml
  - time: 20250904130200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250904142900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250904170500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250904192500
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250904201200
    name: 开水
    amount: 240
    unit: ml
med:
  - time: 20250904113000
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250904130200
    name: selenium
    amount: 200
    unit: μg
  - time: 20250904130200
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
