date: 20250612
food:
  - time: 20250612094300
    name: 人参果
    amount: 90
    unit: g  
  - time: 20250612094400
    name: 李子
    amount: 40
    unit: g   
  - time: 20250612190100
    name: 荔枝
    amount: 20
    unit: g
  
  - time: 20250612094600
    name: 土豆
    amount: 140
    unit: g
  - time: 20250612094600
    name: 南瓜
    amount: 55
    unit: g
  - time: 20250612094600
    name: 卤牛肚2506a
    amount: 0
    unit: g
  - time: 20250612190100
    name: 宣掌柜五香虎皮鸡爪
    amount: 60
    unit: g
  - time: 20250612094600
    name: 芦笋
    amount: 120
    unit: g
  - time: 20250612094600
    name: 枸杞
    amount: 3.0
    unit: g
  - time: 20250612094600
    name: 油莎豆
    amount: 5.0
    unit: g
  
  - time: 20250612100600
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250612100600
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250612100600
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g
  
  - time: 20250612101500
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250612101500
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g  
  
  - time: 20250612145700
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250612145700
    name: 域尚楼兰沙棘全果原浆
    amount: 20.0
    unit: g
  - time: 20250612145700
    name: 菊粉
    amount: 5
    unit: g
  
  - time: 20250612145900
    name: 人参果
    amount: 45
    unit: g
  - time: 20250612150000
    name: 李子
    amount: 90
    unit: g
  - time: 20250612150200
    name: 荔枝
    amount: 40
    unit: g  
  
  - time: 20250612150400
    name: 大米
    amount: 40
    unit: g
  - time: 20250612150400
    name: 黑青稞
    amount: 20
    unit: g
  - time: 20250612150400
    name: 绿豆
    amount: 10
    unit: g
  - time: 20250612150400
    name: 卤羊腿肉2506a
    amount: 50
    unit: g
  - time: 20250612150400
    name: 木耳
    amount: 0
    unit: g
  - time: 20250612150400
    name: 菜心
    amount: 160.0
    unit: g
  - time: 20250612150400
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250612150400
    name: 油
    amount: 0.5
    unit: g  
  
  - time: 20250612152600
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250612152600
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g  
  
  - time: 20250612190000
    name: 橙
    amount: 125
    unit: g
  
  - time: 20250612190500
    name: 馒头2506b
    amount: 1
    unit: 个
  - time: 20250612190500
    name: 鸡蛋
    amount: 48
    unit: g
  - time: 20250612190500
    name: 苦菊
    amount: 120
    unit: g
  - time: 20250612190500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250612190500
    name: 油
    amount: 0.5
    unit: g
  
  - time: 20250612192200
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250612192200
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250612082600
    name: 开水
    amount: 200
    unit: ml
  - time: 20250612092100
    name: 开水
    amount: 250
    unit: ml  
  - time: 20250612101500
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250612102300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250612130100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250612152600
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20250612170200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250612192200
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250612194000
    name: 开水
    amount: 165
    unit: ml
med:
  - time: 20250612150400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250612102300
    name: selenium
    amount: 200
    unit: μg
  - time: 20250612102300
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
