date: 20250712
food:
  - time: 20250712091000
    name: 橙
    amount: 130
    unit: g

  - time: 20250712091300
    name: 馒头2507b
    amount: 1
    unit: 个
  - time: 20250712091300
    name: 南瓜
    amount: 75
    unit: g
  - time: 20250712091300
    name: 宣掌柜五香虎皮鸡爪
    amount: 60
    unit: g    
  - time: 20250712091300
    name: 粉蒸肉2507a
    amount: 30
    unit: g    
  - time: 20250712091300
    name: 芦笋
    amount: 140
    unit: g

  - time: 20250712092400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250712092400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250712092400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250712094300
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250712094300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250712140900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250712140900
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250712140900
    name: 艾斯蔗菊粉
    amount: 10
    unit: g

  - time: 20250712141000
    name: 李子
    amount: 200
    unit: g
    
  - time: 20250712141100
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20250712141100
    name: 福润东方有机小米
    amount: 20.0
    unit: g
  - time: 20250712141100
    name: 泉嫁艳青麦仁
    amount: 50.0
    unit: g
  - time: 20250712141100
    name: 菜心
    amount: 170
    unit: g
  - time: 20250712141100
    name: 胡萝卜
    amount: 100
    unit: g
  - time: 20250712141100
    name: 黑胡椒风味芊芊鱼排
    amount: 90
    unit: g
  - time: 20250712141100
    name: 炸鸡裹粉
    amount: 10
    unit: g
  - time: 20250712141100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250712141100
    name: 油
    amount: 3.5
    unit: g

  - time: 20250712143800
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250712143800
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250712194000
    name: 梨
    amount: 250
    unit: g

  - time: 20250712194300
    name: 裕湘A+细挂面
    amount: 60
    unit: g
  - time: 20250712194300
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250712194300
    name: 油菜
    amount: 75
    unit: g
  - time: 20250712194300
    name: 单山蘸水
    amount: 3
    unit: g
  - time: 20250712194300
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250712194300
    name: 油
    amount: 0.5
    unit: g

  - time: 20250712200200
    name: 黄油玫瑰饼
    amount: 120
    unit: g
  - time: 20250712200200
    name: 奶粉
    amount: 20
    unit: g
  - time: 20250712200200
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250712075700
    name: 开水
    amount: 200
    unit: ml
  - time: 20250712085200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250712093200
    name: 粥水
    amount: 350
    unit: ml
  - time: 20250712094300
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20250712104400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250712121600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250712143800
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250712161800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250712174900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250712200200
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250712203900
    name: 开水
    amount: 150
    unit: ml
med:
  - time: 20250712094300
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250712104400
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20250712104400
    name: selenium
    amount: 200
    unit: μg
  - time: 20250712104400
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
