date: 20250611
food:
  - time: 20250611111300
    name: 人参果
    amount: 135
    unit: g  
  
  - time: 20250611111600
    name: 馒头2506a
    amount: 1
    unit: 个
  - time: 20250611111600
    name: 南瓜
    amount: 65
    unit: g
  - time: 20250611111600
    name: 卤牛肚2506a
    amount: 70
    unit: g
  - time: 20250611111600
    name: 芦笋
    amount: 130
    unit: g
  - time: 20250611111600
    name: 枸杞
    amount: 3.0
    unit: g
  - time: 20250611111600
    name: 油莎豆
    amount: 5.0
    unit: g
  - time: 20250611111600
    name: 姜
    amount: 5.0
    unit: g
  
  - time: 20250611114100
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250611114100
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250611114100
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g
    
  - time: 20250611101300
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250611101300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g  
  
  - time: 20250611182300
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250611182300
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250611182300
    name: 菊粉
    amount: 10
    unit: g
  
  - time: 20250611182400
    name: 李子
    amount: 140
    unit: g
  
  - time: 20250611182800
    name: 土豆
    amount: 190
    unit: g
  - time: 20250611182800
    name: 三都港黄鱼鯗
    amount: 70
    unit: g
    log:
      - 总重93.5g，骨重5.5g。
      - 把水擦净。
      - 不预热、上下火、上层，180°C+15分钟。
      - 翻面，上下火，上层，220°C+5分钟。
  - time: 20250611182800
    name: 快菜
    amount: 220
    unit: g
  - time: 20250611182800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250611182800
    name: 油
    amount: 0.5
    unit: g
  
  - time: 20250611123000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250611123000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g  
    
  - time: 20250611185300
    name: 橙
    amount: 140
    unit: g
    
  - time: 20250611190000
    name: 馒头2506b
    amount: 1
    unit: 个
  - time: 20250611190000
    name: 鸡蛋
    amount: 48
    unit: g
  - time: 20250611190000
    name: 苦菊
    amount: 150
    unit: g
  - time: 20250611190000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250611190000
    name: 油
    amount: 0.5
    unit: g
  
  - time: 20250611192000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250611192000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250611095400
    name: 开水
    amount: 200
    unit: ml
  - time: 20250611105500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250611111600
    name: 汤水
    amount: 350
    unit: ml
  - time: 20250611101300
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250611130400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250611134600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250611123000
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250611150300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250611160900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250611192000
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250611202900
    name: 开水
    amount: 230
    unit: ml
med:
  - time: 20250611182800
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250611130400
    name: selenium
    amount: 200
    unit: μg
  - time: 20250611130400
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
