date: 20250618
food:
  - time: 20250618045300
    name: 人参果
    amount: 130
    unit: g

  - time: 20250618124700
    name: 扬农沁香米
    amount: 10
    unit: g
  - time: 20250618124700
    name: 泉嫁艳青麦仁
    amount: 20
    unit: g
  - time: 20250618124700
    name: 绿豆
    amount: 20
    unit: g
  - time: 20250618045600
    name: 南瓜
    amount: 50
    unit: g
  - time: 20250618190100
    name: 育青琵琶腿
    amount: 65
    unit: g
  - time: 20250618045600
    name: 秋葵
    amount: 165
    unit: g

  - time: 20250618052300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250618052300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250618052300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250618053900
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250618053900
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250618124200
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250618124200
    name: 域尚楼兰沙棘全果原浆
    amount: 20.0
    unit: g
  - time: 20250618124200
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20250618124300
    name: 李子
    amount: 135
    unit: g

  - time: 20250618124700
    name: 扬农沁香米
    amount: 40
    unit: g
  - time: 20250618124700
    name: 福润东方有机小米
    amount: 20
    unit: g
  - time: 20250618124700
    name: 泉嫁艳青麦仁
    amount: 20
    unit: g
  - time: 20250618124700
    name: 粉蒸肉2506a
    amount: 40
    unit: g
  - time: 20250618124700
    name: 油菜
    amount: 230
    unit: g
  - time: 20250618124700
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250618124700
    name: 油
    amount: 0.5
    unit: g

  - time: 20250618132600
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250618132600
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250618195500
    name: 橙
    amount: 120
    unit: g

  - time: 20250618195700
    name: 裕湘A+细挂面
    amount: 25
    unit: g
  - time: 20250618195700
    name: 鸡蛋
    amount: 46.0
    unit: g
  - time: 20250618195700
    name: 圆白菜
    amount: 57.5
    unit: g
  - time: 20250618195700
    name: 胡萝卜
    amount: 50
    unit: g
  - time: 20250618195700
    name: 洋葱
    amount: 50
    unit: g
  - time: 20250618195700
    name: 南瓜
    amount: 40
    unit: g
  - time: 20250618195700
    name: 枸杞
    amount: 3.0
    unit: g
  - time: 20250618195700
    name: 油莎豆
    amount: 5.0
    unit: g
  - time: 20250618195700
    name: 姜
    amount: 5.0
    unit: g
  - time: 20250618195700
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250618195700
    name: 味精
    amount: 0.5
    unit: g
  - time: 20250618195700
    name: 香油
    amount: 0.5
    unit: g

  - time: 20250618203800
    name: 伊利脱脂奶粉
    amount: 20.0
    unit: g
  - time: 20250618203800
    name: 天然可可粉
    amount: 2.0
    unit: g
water:
  - time: 20250618043800
    name: 开水
    amount: 200
    unit: ml
  - time: 20250618044100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250618053900
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250618060500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250618065000
    name: 开水
    amount: 225
    unit: ml
  - time: 20250618104100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250618132600
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20250618140200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250618160000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250618195700
    name: 汤水
    amount: 200
    unit: ml
  - time: 20250618203800
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 3700
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250618053900
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250618060500
    name: selenium
    amount: 200
    unit: μg
  - time: 20250618060500
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
