date: 20251116
food:
  - time: 20251116134600
    name: 橙
    amount: 115
    unit: g

  - time: 20251116135200
    name: 土豆
    amount: 120
    unit: g
  - time: 20251116135200
    name: 阿拉里玉米面条
    amount: 30
    unit: g
  - time: 20251116135200
    name: 粮农星厨老母鸡汤
    amount: 355.0
    unit: g
  - time: 20251116135200
    name: 南瓜
    amount: 65
    unit: g
  - time: 20251116135200
    name: 胡萝卜
    amount: 50
    unit: g
  - time: 20251116135200
    name: 洋葱
    amount: 50
    unit: g
  - time: 20251116135200
    name: 圆白菜
    amount: 50
    unit: g
  - time: 20251116135200
    name: 西兰苔
    amount: 150
    unit: g
  - time: 20251116135200
    name: 王致和减盐玫瑰腐乳
    amount: 15.0
    unit: g

  - time: 20251116142300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251116142300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251116142300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251116143200
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251116143200
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20251116211900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251116211900
    name: 东棘沙棘原浆
    amount: 30.0
    unit: g
  - time: 20251116211900
    name: 百香果
    amount: 45
    unit: g
  - time: 20251116211900
    name: 菊粉
    amount: 9.0
    unit: g
  - time: 20251116211900
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20251116212100
    name: 梨
    amount: 85
    unit: g

  - time: 20251116212500
    name: 全麦面包2510b
    amount: 140
    unit: g
  - time: 20251116212500
    name: 三文鱼
    amount: 100
    unit: g
  - time: 20251116212500
    name: 黄心菜
    amount: 250
    unit: g
  - time: 20251116212500
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20251116212500
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251116220600
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251116220600
    name: 兴科可可粉
    amount: 4.5
    unit: g
water:
  - time: 20251116121600
    name: 开水
    amount: 150
    unit: ml
  - time: 20251116132800
    name: 开水
    amount: 250
    unit: ml
  - time: 20251116143200
    name: 咖啡
    amount: 120.0
    unit: ml
  - time: 20251116152000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251116155500
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251116163600
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251116165200
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251116175400
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251116190200
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251116220600
    name: 可可奶
    amount: 121.0
    unit: ml
  - time: 20251116221400
    name: 红茶
    amount: 250
    unit: ml
med:
  - time: 20251116143200
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251116152000
    name: selenium
    amount: 200
    unit: μg
  - time: 20251116152000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
