date: 20250903
food:
  - time: 20250903132800
    name: 番茄酱
    amount: 17.5
    unit: g
  - time: 20250903132800
    name: 棘密西梅原浆
    amount: 53.0
    unit: g
  - time: 20250903132800
    name: 菊粉
    amount: 7.0
    unit: g

  - time: 20250903133000
    name: 梨
    amount: 310.0
    unit: g

  - time: 20250903192600
    name: 馒头2508c
    amount: 1
    unit: 个
  - time: 20250903192600
    name: 广信水煮三文鱼
    amount: 132.5
    unit: g
  - time: 20250903192600
    name: 双笑咸山黄皮果
    amount: 10.5
    unit: g
  - time: 20250903192600
    name: 南瓜
    amount: 72.0
    unit: g
  - time: 20250903192600
    name: 西兰花
    amount: 136.5
    unit: g

  - time: 20250903135500
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250903135500
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250903135500
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250903141400
    name: 我的童年纯牛奶粉
    amount: 30.0
    unit: g
  - time: 20250903141400
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20250903191900
    name: 番茄酱
    amount: 15.0
    unit: g
  - time: 20250903191900
    name: 域尚楼兰沙棘全果原浆
    amount: 30
    unit: g
  - time: 20250903191900
    name: 菊粉
    amount: 8.0
    unit: g

  - time: 20250903132900
    name: 葡萄
    amount: 150
    unit: g
  - time: 20250903133300
    name: 杏
    amount: 90
    unit: g

  - time: 20250903192600
    name: 红薯
    amount: 200
    unit: g
  - time: 20250903192600
    name: 粉蒸肉2508c
    amount: 60
    unit: g
  - time: 20250903192600
    name: 油菜
    amount: 150
    unit: g
  - time: 20250903192600
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250903192600
    name: 油
    amount: 0.5
    unit: g

  - time: 20250903195100
    name: 蛋挞2508c
    amount: 1
    unit: 个
  - time: 20250903203200
    name: 我的童年纯牛奶粉
    amount: 30.0
    unit: g
  - time: 20250903203200
    name: 天然可可粉
    amount: 4.5
    unit: g
water:
  - time: 20250903093100
    name: 开水
    amount: 200
    unit: ml
  - time: 20250903102800
    name: 开水
    amount: 250
    unit: ml

  - time: 20250903141400
    name: 咖啡
    amount: 120.5
    unit: ml
  - time: 20250903151400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250903163200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250903192600
    name: 汤水
    amount: 500
    unit: ml
  - time: 20250903203200
    name: 可可奶
    amount: 125.0
    unit: ml
  - time: 20250903220900
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250903141400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250903151400
    name: selenium
    amount: 200
    unit: μg
  - time: 20250903151400
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
