date: 20260114
food:
  - time: 20260114035500
    name: 番石榴
    amount: 170
    unit: g

  - time: 20260114035700
    name: 馒头2601a
    amount: 1
    unit: 个
  - time: 20260114035700
    name: 南瓜
    amount: 120
    unit: g
  - time: 20260114035700
    name: 兔肉
    amount: 150
    unit: g
  - time: 20260114035700
    name: 豆瓣酱
    amount: 10
    unit: g
  - time: 20260114035700
    name: 红菜苔
    amount: 140
    unit: g

  - time: 20260114041700
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260114041700
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260114041700
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260114042800
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20260114042800
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20260114111900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20260114111900
    name: 百香果
    amount: 20
    unit: g
  - time: 20260114111900
    name: 菊粉
    amount: 7.0
    unit: g

  - time: 20260114112000
    name: 猕猴桃
    amount: 85.0
    unit: g
  - time: 20260114112400
    name: 桔柚
    amount: 150
    unit: g

  - time: 20260114113200
    name: 大米
    amount: 80.0
    unit: g
  - time: 20260114113200
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20260114113200
    name: 红豆
    amount: 10.0
    unit: g
  - time: 20260114113200
    name: 松板肉
    amount: 50
    unit: g
  - time: 20260114113200
    name: 大白菜
    amount: 250
    unit: g
  - time: 20260114113200
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20260114113200
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g   

  - time: 20260114122000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20260114122000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
  - time: 20260114122000
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g
water:
  - time: 20260114024400
    name: 开水
    amount: 200
    unit: ml
  - time: 20260114034300
    name: 开水
    amount: 250
    unit: ml
  - time: 20260114042800
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20260114051500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260114073600
    name: 开水
    amount: 250
    unit: ml
  - time: 20260114085600
    name: 开水
    amount: 250
    unit: ml
  - time: 20260114100700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260114122000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20260114140200
    name: 开水
    amount: 150
    unit: ml
  - time: 20260114161200
    name: 开水
    amount: 250
    unit: ml
med:
  - time: 20260114042800
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260114051500
    name: selenium
    amount: 200
    unit: μg
  - time: 20260114051500
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |