date: 20250715
food:
  - time: 20250715064800
    name: 梨
    amount: 275
    unit: g

  - time: 20250715065300
    name: 馒头2507b
    amount: 1
    unit: 个
  - time: 20250715065300
    name: 南瓜
    amount: 45
    unit: g    
  - time: 20250715065300
    name: 粉蒸肉2507a
    amount: 60
    unit: g    
  - time: 20250715065300
    name: 芦笋
    amount: 150
    unit: g

  - time: 20250715070800
    name: 红塔玫瑰黄油饼
    amount: 5
    unit: g
  - time: 20250715070800
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250715070800
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250715070800
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250715071900
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250715071900
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250715121400
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250715121400
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250715155100
    name: 百香果
    amount: 40.0
    unit: g
    
  - time: 20250715155100
    name: 李子
    amount: 160
    unit: g

  - time: 20250715121600
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20250715121600
    name: 福润东方有机小米
    amount: 20.0
    unit: g
  - time: 20250715121600
    name: 泉嫁艳青麦仁
    amount: 50
    unit: g
  - time: 20250715121600
    name: 菜心
    amount: 180
    unit: g
  - time: 20250715121600
    name: 木耳
    amount: 10
    unit: g
  - time: 20250715121600
    name: 黑胡椒风味芊芊鱼排
    amount: 125
    unit: g
  - time: 20250715121600
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250715121600
    name: 油
    amount: 0.5
    unit: g

  - time: 20250715124500
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250715124500
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g    

  - time: 20250715175300
    name: 荔枝
    amount: 100
    unit: g

  - time: 20250715175800
    name: 毛豆仁
    amount: 90.0
    unit: g
  - time: 20250715175800
    name: 裕湘A+细挂面
    amount: 120
    unit: g
  - time: 20250715175800
    name: 油菜
    amount: 100
    unit: g
  - time: 20250715175800
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250715175800
    name: 锦悦和五城茶干
    amount: 100
    unit: g
  - time: 20250715175800
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20250715175800
    name: 油
    amount: 0.5
    unit: g

  - time: 20250715180500
    name: 红塔玫瑰黄油饼
    amount: 50
    unit: g
  - time: 20250715180800
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250715180800
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250715053200
    name: 开水
    amount: 200
    unit: ml
  - time: 20250715063600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250715071900
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250715082700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250715093900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250715124500
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250715132800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250715151800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250715180800
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250715183000
    name: 开水
    amount: 170
    unit: ml
med:
  - time: 20250715071900
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250715082700
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20250715082700
    name: selenium
    amount: 200
    unit: μg
  - time: 20250715082700
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
