date: 20251226
food:
  - time: 20251226015000
    name: 猕猴桃
    amount: 100
    unit: g

  - time: 20251226015200
    name: 馒头2512b
    amount: 1
    unit: 个
  - time: 20251226015200
    name: 南瓜
    amount: 125
    unit: g
  - time: 20251226015200
    name: 荣昌鹅大叔卤鹅
    amount: 70
    unit: g
  - time: 20251226015200
    name: 荣昌鹅大叔卤鹅掌
    amount: 40
    unit: g
  - time: 20251226015200
    name: 西兰苔
    amount: 110
    unit: g

  - time: 20251226023300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251226023300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251226023300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251226023900
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251226023900
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251226085800
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251226085800
    name: 东棘沙棘原浆
    amount: 30
    unit: g
  - time: 20251226085800
    name: 百香果
    amount: 65
    unit: g
  - time: 20251226085800
    name: 菊粉
    amount: 10
    unit: g
  - time: 20251226085800
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20251226085500
    name: 柿子
    amount: 100
    unit: g

  - time: 20251226085800
    name: 大米
    amount: 50.0
    unit: g
  - time: 20251226085800
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20251226085800
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20251226085800
    name: 汾都香红豆
    amount: 10.0
    unit: g
  - time: 20251226085800
    name: 豌豆苗
    amount: 150
    unit: g
  - time: 20251226085800
    name: 炖猪扇骨2512a
    amount: 70
    unit: g
  - time: 20251226085800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251226085800
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251226091800
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251226091800
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
f:
  - time: 20251226220000
    name: 山药豆
    amount: 50
    unit: g
  - time: 20251226220000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20251226220000
    name: 豌豆苗
    amount: 120
    unit: g
  - time: 20251226220000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251226220000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251226055000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251226055000
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251226004200
    name: 开水
    amount: 200
    unit: ml
  - time: 20251226013800
    name: 开水
    amount: 250
    unit: ml
  - time: 20251226023900
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251226025400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251226043900
    name: 开水
    amount: 250
    unit: ml
  - time: 20251226053000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251226065300
    name: 开水
    amount: 250
    unit: ml
  - time: 20251226073200
    name: 开水
    amount: 300
    unit: ml
  - time: 20251226091800
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251226103900
    name: 开水
    amount: 200
    unit: ml

  - time: 20251226161200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251226055000
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20251226202800
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20251226023900
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251226025400
    name: selenium
    amount: 200
    unit: μg
  - time: 20251226025400
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |