date: 20250820
food:
  - time: 20250820123300
    name: 李子
    amount: 85
    unit: g

  - time: 20250820123700
    name: 馒头2508b
    amount: 1
    unit: 个
  - time: 20250820123700
    name: 粉蒸肉2508b
    amount: 100
    unit: g
  - time: 20250820123700
    name: 南瓜
    amount: 83.0
    unit: g
  - time: 20250820123700
    name: 西兰花
    amount: 130
    unit: g

  - time: 20250820125200
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250820125200
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250820125200
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250820131300
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250820131300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250820150400
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250820150400
    name: 域尚楼兰沙棘全果原浆
    amount: 30
    unit: g
  - time: 20250820150400
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20250820183700
    name: 芒果
    amount: 280.0
    unit: g
    
  - time: 20250820184000
    name: 扬农沁香米
    amount: 45
    unit: g
  - time: 20250820184000
    name: 紫米
    amount: 15
    unit: g
  - time: 20250820184000
    name: 粉蒸肉2508b
    amount: 100
    unit: g
  - time: 20250820184000
    name: 芥兰
    amount: 150
    unit: g
  - time: 20250820184000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250820184000
    name: 油
    amount: 0.5
    unit: g

  - time: 20250820190000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250820190000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
    
  - time: 20250820234300
    name: 杏
    amount: 52.0
    unit: g

  - time: 20250820235100
    name: 咖喱鸡肉2508a
    amount: 150
    unit: g
  - time: 20250820235100
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250820235100
    name: 油菜
    amount: 15.0
    unit: g
  - time: 20250820235100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250820235100
    name: 油
    amount: 0.5
    unit: g

  - time: 20250820000900
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250820000900
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250820102700
    name: 开水
    amount: 200
    unit: ml
  - time: 20250820121500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250820131300
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20250820142600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250820144900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250820165700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250820185000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250820000900
    name: 可可奶
    amount: 80.5
    unit: ml
  - time: 20250820003400
    name: 开水
    amount: 250
    unit: ml
med:
  - time: 20250820131300
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250820142600
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20250820142600
    name: selenium
    amount: 200
    unit: μg
  - time: 20250820142600
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
