date: 20250625
food:
  - time: 20250625083600
    name: 人参果
    amount: 130
    unit: g

  - time: 20250625084000
    name: 馒头2506c
    amount: 1
    unit: 个
  - time: 20250625084000
    name: 南瓜
    amount: 40
    unit: g
  - time: 20250625190100
    name: 粉蒸肉2506a
    amount: 40
    unit: g
  - time: 20250625084000
    name: 秋葵
    amount: 90
    unit: g
  - time: 20250625142200
    name: 中盐绿色低钠湖盐
    amount: 0.5
    unit: g

  - time: 20250625091300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250625091300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250625091300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250625091300
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250625091300
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250625141500
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250625141500
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250625141500
    name: 艾斯蔗菊粉
    amount: 7.0
    unit: g

  - time: 20250625141700
    name: 杏
    amount: 140
    unit: g

  - time: 20250625142200
    name: 扬农沁香米
    amount: 20
    unit: g
  - time: 20250625142200
    name: 福润东方有机小米
    amount: 20
    unit: g
  - time: 20250625142200
    name: 泉嫁艳青麦仁
    amount: 40
    unit: g
  - time: 20250625142200
    name: 腌鸡腿肉2504b
    amount: 50
    unit: g
  - time: 20250625142200
    name: 木耳
    amount: 10
    unit: g
  - time: 20250625142200
    name: 菜心
    amount: 160
    unit: g
  - time: 20250625142200
    name: 胡萝卜
    amount: 75
    unit: g
  - time: 20250625142200
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20250625142200
    name: 油
    amount: 0.5
    unit: g

  - time: 20250625150500
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250625150500
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250625195600
    name: 橙
    amount: 125
    unit: g

  - time: 20250625200000
    name: 土豆
    amount: 100
    unit: g
  - time: 20250625200000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250625200000
    name: 香油臭豆腐乳
    amount: 10
    unit: g
  - time: 20250625200000
    name: 油菜
    amount: 150
    unit: g
  - time: 20250625200000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250625201700
    name: 油
    amount: 0.5
    unit: g

  - time: 20250625204000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250625204000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250625072700
    name: 开水
    amount: 200
    unit: ml
  - time: 20250625082400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250625085700
    name: 粥水
    amount: 400
    unit: ml
  - time: 20250625091300
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20250625101300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250625113900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250625150500
    name: 咖啡
    amount: 89.0
    unit: ml
  - time: 20250625163800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250625173100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250625204000
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250625211500
    name: 开水
    amount: 0
    unit: ml
med:
  - time: 20250625091300
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250625101300
    name: selenium
    amount: 200
    unit: μg
  - time: 20250625101300
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
