date: 20260211
food:
  - time: 20260211052800
    name: 番石榴
    amount: 150
    unit: g

  - time: 20260211053200
    name: 萝卜糕2602a
    amount: 150
    unit: g
  - time: 20260211053200
    name: 山药
    amount: 100.0
    unit: g
  - time: 20260211053200
    name: 南瓜
    amount: 40.0
    unit: g
  - time: 20260211053200
    name: 红菜苔
    amount: 130
    unit: g
  - time: 20260211053200
    name: 十三村原味腐乳
    amount: 8
    unit: g

  - time: 20260211054500
    name: 新疆手工切糕
    amount: 35
    unit: g
  - time: 20260211054500
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260211054500
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260211054500
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260211055400
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260211055400
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260211120000
    name: 番茄酱
    amount: 25
    unit: g
  - time: 20260211120000
    name: 戈壁密码有机沙棘原浆
    amount: 25
    unit: g
  - time: 20260211120000
    name: 菊粉
    amount: 15.0
    unit: g

  - time: 20260211114500
    name: 草莓
    amount: 85
    unit: g
  - time: 20260211114500
    name: 猕猴桃
    amount: 140
    unit: g
  - time: 20260211114500
    name: 简醇0蔗糖酸奶
    amount: 150
    unit: g

  - time: 20260211114800
    name: 一品寒香大米
    amount: 70.0
    unit: g
  - time: 20260211114800
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20260211114800
    name: 红豆
    amount: 10.0
    unit: g
  - time: 20260211114800
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20260211114800
    name: 炖鲟鱼2602a
    amount: 90
    unit: g
  - time: 20260211114800
    name: 黄心菜
    amount: 150
    unit: g
  - time: 20260211114800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260211114800
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260211120500
    name: 河套纯牛奶粉
    amount: 0
    unit: g
  - time: 20260211120500
    name: 品儿Piner天然可可粉
    amount: 0
    unit: g
water:
  - time: 20260211042200
    name: 开水
    amount: 200
    unit: ml
  - time: 20260211051500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260211055400
    name: 咖啡
    amount: 102.0
    unit: ml
  - time: 20260211062000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260211075200
    name: 开水
    amount: 250
    unit: ml
  - time: 202602110084100
    name: 开水
    amount: 250
    unit: ml
  - time: 20260211102500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260211120500
    name: 可可奶
    amount: 105.5
    unit: ml
  - time: 20260211134600
    name: 开水
    amount: 250
    unit: ml
med:
  - time: 20260211055400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260211062000
    name: selenium
    amount: 200
    unit: μg
  - time: 20260211062000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
