date: 20251026
food:
  - time: 20251026103700
    name: 猕猴桃
    amount: 59.0
    unit: g
  - time: 20251026103800
    name: 阿拉里玉米面条
    amount: 100
    unit: g
  - time: 20251026103800
    name: 炖排骨2510d
    amount: 33.0
    unit: g
  - time: 20251026103800
    name: 鸡蛋
    amount: 37.5
    unit: g
  - time: 20251026103800
    name: 乌塌菜
    amount: 136.5
    unit: g
  - time: 20251026103800
    name: 中盐绿色低钠湖盐
    amount: 3.0
    unit: g
  - time: 20251026103800
    name: 味精
    amount: 1.5
    unit: g
  - time: 20251026105400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251026105400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251026105400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g
  - time: 20251026110800
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251026110800
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20251026131700
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251026131700
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20251026131700
    name: 菊粉
    amount: 15
    unit: g
  - time: 20251026131700
    name: 百香果
    amount: 50.0
    unit: g
  - time: 20251026131700
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20251026180400
    name: 柿子
    amount: 100
    unit: g
  - time: 20251026180400
    name: 山楂
    amount: 50
    unit: g

  - time: 20251026131900
    name: 馒头2510c
    amount: 1
    unit: 个
  - time: 20251026131900
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20251026131900
    name: 菠菜
    amount: 160
    unit: g
  - time: 20251026131900
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251026131900
    name: 味精
    amount: 1.0
    unit: g
  - time: 20251026131900
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251026182500
    name: 如紫兰果仁月饼
    amount: 32.0
    unit: g
  - time: 20251026182500
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251026182500
    name: 兴科可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251026091100
    name: 开水
    amount: 200
    unit: ml
  - time: 20251026102200
    name: 开水
    amount: 250
    unit: ml
  - time: 20251026103800
    name: 汤水
    amount: 500
    unit: ml
  - time: 20251026110800
    name: 咖啡
    amount: 120.0
    unit: ml
  - time: 20251026113600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251026134100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251026141600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251026150300
    name: 开水
    amount: 250
    unit: ml
  - time: 20251026162000
    name: 开水
    amount: 250
    unit: ml

  - time: 20251026182500
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20251026200900
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20251026110800
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251026113600
    name: selenium
    amount: 200
    unit: μg
  - time: 20251026113600
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
