date: 20250704
food:
  - time: 20250704105500
    name: 油桃
    amount: 142
    unit: g

  - time: 20250704105800
    name: 馒头2507a
    amount: 1
    unit: 个
  - time: 20250704105800
    name: 南瓜
    amount: 40
    unit: g
  - time: 20250704190100
    name: 卤牛肚2506b
    amount: 45
    unit: g
  - time: 20250704105800
    name: 芦笋
    amount: 130
    unit: g
  - time: 20250704105800
    name: 中盐绿色低钠湖盐
    amount: 0.5
    unit: g

  - time: 20250704111100
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250704111100
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250704111100
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250704092800
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250704092800
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250704155100
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250704155100
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250704155100
    name: 艾斯蔗菊粉
    amount: 10
    unit: g

  - time: 20250704155200
    name: 杏
    amount: 66.0
    unit: g
  - time: 20250704155600
    name: 李子
    amount: 50
    unit: g

  - time: 20250704155500
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20250704155500
    name: 福润东方有机小米
    amount: 20.0
    unit: g
  - time: 20250704155500
    name: 泉嫁艳青麦仁
    amount: 70.0
    unit: g
  - time: 20250704155500
    name: 腌鸡腿肉2504b
    amount: 50.0
    unit: g
  - time: 20250704155500
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20250704155500
    name: 油菜
    amount: 150.0
    unit: g
  - time: 20250704155500
    name: 胡萝卜
    amount: 100
    unit: g
  - time: 20250704155500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250704155500
    name: 油
    amount: 0.5
    unit: g

  - time: 20250704163000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250704163000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250704191500
    name: 圣女果
    amount: 187.5
    unit: g
    log:
      - 糖珀琥85.0g
      - 圣女果102.5g

  - time: 20250704192000
    name: 土豆
    amount: 150
    unit: g
  - time: 20250704192000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250704192000
    name: 香油臭豆腐乳
    amount: 20
    unit: g
  - time: 20250704192000
    name: 油菜
    amount: 120
    unit: g
  - time: 20250704192000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250704192000
    name: 油
    amount: 0.5
    unit: g

  - time: 20250704193700
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250704193700
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250704092500
    name: 开水
    amount: 200
    unit: ml
  - time: 20250704103600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250704092800
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250704125800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250704134700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250704163000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250704181000
    name: 开水
    amount: 250
    unit: ml

  - time: 20250704173000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250704192000
    name: 汤水
    amount: 200
    unit: ml
  - time: 20250704193700
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250704211900
    name: 开水
    amount: 125
    unit: ml
med:
  - time: 20250704092800
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250704125800
    name: selenium
    amount: 200
    unit: μg
  - time: 20250704125800
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
