date: 20260222
food:
  - time: 20260222973300
    name: 释迦果
    amount: 120
    unit: g
  - time: 20260222973300
    name: 苹果
    amount: 0
    unit: g

  - time: 20260222073800
    name: 萝卜糕2602a
    amount: 180
    unit: g
  - time: 20260222073800
    name: 兰小糯糯玉米
    amount: 110
    unit: g
  - time: 20260222073800
    name: 南瓜
    amount: 75
    unit: g
  - time: 20260222073800
    name: 西兰花
    amount: 100
    unit: g
  - time: 20260222073800
    name: 十三村原味腐乳
    amount: 8.0
    unit: g

  - time: 20260222080300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260222080300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260222080300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260222081600
    name: 河套纯牛奶粉
    amount: 26.0
    unit: g
  - time: 20260222081600
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260222134300
    name: 番茄酱
    amount: 20.0
    unit: g
  - time: 20260222134300
    name: 戈壁密码有机沙棘原浆
    amount: 25
    unit: g
  - time: 20260222134300
    name: 菊粉
    amount: 10
    unit: g

  - time: 20260222134500
    name: 一品寒香大米
    amount: 45.0
    unit: g
  - time: 20260222134500
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20260222134500
    name: 红豆
    amount: 10.0
    unit: g
  - time: 20260222134500
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20260222134500
    name: 炖鲟鱼2602b
    amount: 100
    unit: g
  - time: 20260222134500
    name: 芹菜
    amount: 220
    unit: g
  - time: 20260222134500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260222134500
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260222153000
    name: 柿子
    amount: 200
    unit: g

  - time: 20260222153700
    name: 河套纯牛奶粉
    amount: 25.5
    unit: g
  - time: 20260222153700
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260222063200
    name: 开水
    amount: 200
    unit: ml
  - time: 20260222072500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260222081600
    name: 咖啡
    amount: 102.0
    unit: ml
  - time: 20260222085500
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260222093600
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260222101300
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260222112600
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260222123500
    name: 红茶
    amount: 250
    unit: ml
  - time: 20260222153700
    name: 可可奶
    amount: 100.0
    unit: ml
  - time: 20260222142700
    name: 红茶
    amount: 250
    unit: ml
med:
  - time: 20260222081600
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260222085500
    name: selenium
    amount: 200
    unit: μg
  - time: 20260222085500
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
