date: 20251105
food:
  - time: 20251105061500
    name: 番石榴
    amount: 240
    unit: g

  - time: 20251105063000
    name: 馒头2510c
    amount: 1
    unit: 个
  - time: 20251105063000
    name: 炖排骨2511a
    amount: 35
    unit: g
  - time: 20251105063000
    name: 红薯
    amount: 30
    unit: g
  - time: 20251105063000
    name: 秋葵
    amount: 140.0
    unit: g

  - time: 20251105065000
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251105065000
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251105065000
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251105071000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251105071000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251105125000
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251105125000
    name: 东棘沙棘原浆
    amount: 30
    unit: g
  - time: 20251105125000
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20251105130200
    name: 猕猴桃
    amount: 65
    unit: g

  - time: 20251105131000
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20251105131000
    name: 紫米
    amount: 15.0
    unit: g
  - time: 20251105131000
    name: 绿豆
    amount: 5.0
    unit: g
  - time: 20251105131000
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20251105131000
    name: 大成奥尔良味香煎鸡扒
    amount: 76.0
    unit: g
  - time: 20251105131000
    name: 油菜
    amount: 160
    unit: g
  - time: 20251105131000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251105131000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g
    
  - time: 20251105135000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251105135000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251105175000
    name: 猕猴桃
    amount: 65
    unit: g
    
  - time: 20251105180000
    name: 阿拉里玉米面条
    amount: 40.0
    unit: g
  - time: 20251105180000
    name: 鸡蛋
    amount: 50
    unit: g
  - time: 20251105180000
    name: 南瓜
    amount: 50
    unit: g
  - time: 20251105180000
    name: 胡萝卜
    amount: 50
    unit: g
  - time: 20251105180000
    name: 洋葱
    amount: 50.0
    unit: g
  - time: 20251105180000
    name: 圆白菜
    amount: 50
    unit: g
  - time: 20251105180000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251105180000
    name: 味精
    amount: 0.5
    unit: g
  - time: 20251105180000
    name: 王致和减盐玫瑰腐乳
    amount: 10
    unit: g

  - time: 20251105190000
    name: 伊利脱脂奶粉
    amount: 20.0
    unit: g
  - time: 20251105190000
    name: 兴科可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251105115300
    name: 开水
    amount: 200
    unit: ml
  - time: 20251105130400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251105071000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251105143000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251105151800
    name: 开水
    amount: 250
    unit: ml
  - time: 20251105161300
    name: 开水
    amount: 250
    unit: ml
  - time: 20251105174400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251105190000
    name: 可可奶
    amount: 120.5
    unit: ml
  - time: 20251105200900
    name: 开水
    amount: 100
    unit: ml
med:
  - time: 20251105071000
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251105143000
    name: selenium
    amount: 200
    unit: μg
  - time: 20251105143000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
