date: 20250908
food:
  - time: 20250908135700
    name: 棘密西梅原浆
    amount: 50
    unit: g
  - time: 20250908135700
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20250908135700
    name: 菊粉
    amount: 5.0
    unit: g

  - time: 20250908135900
    name: 冬枣
    amount: 135
    unit: g
  - time: 20250908140900
    name: 咖喱鸡肉2508b
    amount: 150
    unit: g
  - time: 20250908140900
    name: 南瓜
    amount: 75
    unit: g
  - time: 20250908140900
    name: 西兰花
    amount: 150
    unit: g

  - time: 20250908141600
    name: 伯香村五仁月饼
    amount: 0
    unit: g
  - time: 20250908141600
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250908141600
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250908141600
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250908143800
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250908143800
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250908120000
    name: 白桃
    amount: 200
    unit: g

  - time: 20250908121000
    name: 扬农沁香米
    amount: 40
    unit: g
  - time: 20250908121000
    name: 紫米
    amount: 15
    unit: g
  - time: 20250908121000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250908121000
    name: 小白菜
    amount: 150
    unit: g
  - time: 20250908121000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250908121000
    name: 油
    amount: 0.5
    unit: g

  - time: 20250908133000
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250908133000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250908193800
    name: 梨
    amount: 201.0
    unit: g

  - time: 20250908194300
    name: 安尼斯意大利面
    amount: 5.0
    unit: g
  - time: 20250908194300
    name: 土豆
    amount: 150
    unit: g
  - time: 20250908194300
    name: 猪舌
    amount: 30.0
    unit: g
  - time: 20250908194300
    name: 胡萝卜
    amount: 55.0
    unit: g
  - time: 20250908194300
    name: 洋葱
    amount: 62.0
    unit: g
  - time: 20250908194300
    name: 唯加南洋风味咖喱酱
    amount: 20
    unit: g
  - time: 20250908194300
    name: 油菜
    amount: 150
    unit: g
  - time: 20250908194300
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250908194300
    name: 油
    amount: 0.5
    unit: g

  - time: 20250908204500
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20250908204500
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250908115800
    name: 开水
    amount: 200
    unit: ml
  - time: 20250908131300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250908143800
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250908153800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250908163600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250908174200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250908204500
    name: 可可奶
    amount: 70.0
    unit: ml
  - time: 20250908214500
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250908143800
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250908153800
    name: selenium
    amount: 200
    unit: μg
  - time: 20250908153800
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
