date: 20250713
food:
  - time: 20250713111000
    name: 橙
    amount: 120
    unit: g

  - time: 20250713111600
    name: 馒头2507b
    amount: 1
    unit: 个
  - time: 20250713111600
    name: 南瓜
    amount: 70
    unit: g    
  - time: 20250713111600
    name: 康大熏香兔前腿
    amount: 55
    unit: g    
  - time: 20250713111600
    name: 芦笋
    amount: 140
    unit: g

  - time: 20250713113700
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250713113700
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250713113700
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250713114400
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250713114400
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250713181900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250713181900
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250713181900
    name: 艾斯蔗菊粉
    amount: 14.0
    unit: g

  - time: 20250713182000
    name: 李子
    amount: 75
    unit: g

  - time: 20250713182900
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20250713182900
    name: 福润东方有机小米
    amount: 20.0
    unit: g
  - time: 20250713182900
    name: 泉嫁艳青麦仁
    amount: 40
    unit: g
  - time: 20250713182900
    name: 油菜
    amount: 150
    unit: g
  - time: 20250713182900
    name: 木耳
    amount: 10
    unit: g
  - time: 20250713182900
    name: 腌鸡腿肉2507a
    amount: 50
    unit: g
  - time: 20250713182900
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250713182900
    name: 油
    amount: 0.5
    unit: g
    
  - time: 20250713133000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250713133000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250713183000
    name: 李子
    amount: 75
    unit: g

  - time: 20250713190000
    name: 裕湘A+细挂面
    amount: 60
    unit: g
  - time: 20250713190000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250713190000
    name: 油菜
    amount: 100
    unit: g
  - time: 20250713190000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250713190000
    name: 油
    amount: 0.5
    unit: g
    
  - time: 20250713190700
    name: 奶粉
    amount: 20
    unit: g
  - time: 20250713190700
    name: 天然可可粉
    amount: 3.5
    unit: g
water:
  - time: 20250713093600
    name: 开水
    amount: 200
    unit: ml
  - time: 20250713105600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250713114400
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250713123700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250713135000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250713133000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250713160800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250713190700
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250713203100
    name: 开水
    amount: 250
    unit: ml
med:
  - time: 20250713114400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250713123700
    name: selenium
    amount: 200
    unit: μg
  - time: 20250713123700
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
