date: 20250708
food:
  - time: 20250708071900
    name: 蜜桃
    amount: 251.0
    unit: g
 
  - time: 20250708072200
    name: 馒头2507a
    amount: 1
    unit: 个
  - time: 20250708072200
    name: 南瓜
    amount: 41.0
    unit: g
  - time: 20250708190100
    name: 宣掌柜五香虎皮鸡爪
    amount: 180
    unit: g
  - time: 20250708072200
    name: 芦笋
    amount: 160
    unit: g
  - time: 20250708072200
    name: 中盐绿色低钠湖盐
    amount: 0.5
    unit: g

  - time: 20250708073500
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250708073500
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250708073500
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250708074400
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250708074400
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250708120000
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250708120000
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250708120000
    name: 艾斯蔗菊粉
    amount: 15.0
    unit: g

  - time: 20250708120200
    name: 李子
    amount: 86.0
    unit: g
  - time: 20250708120300
    name: 杏
    amount: 58.0
    unit: g

  - time: 20250708120600
    name: 土豆
    amount: 300
    unit: g
  - time: 20250708120600
    name: 毛豆仁
    amount: 200
    unit: g
  - time: 20250708120600
    name: 乐享鸡块
    amount: 220
    unit: g
    log:
      - 实际是外卖炸鸡块
  - time: 20250708120600
    name: 油菜
    amount: 200
    unit: g
  - time: 20250708120600
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250708120600
    name: 油
    amount: 0.5
    unit: g

  - time: 20250708133500
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250708133500
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250708184700
    name: 圣女果
    amount: 153.0
    unit: g

  - time: 20250708185200
    name: 海带
    amount: 10
    unit: g
  - time: 20250708185200
    name: 绿豆
    amount: 40
    unit: g
  - time: 20250708185200
    name: 泉嫁艳青麦仁
    amount: 40
    unit: g
  - time: 20250708185200
    name: 蜂蜜
    amount: 20
    unit: g
  - time: 20250708185200
    name: 乐享鸡块
    amount: 100
    unit: g

  - time: 20250708191900
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250708191900
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250708060700
    name: 开水
    amount: 200
    unit: ml
  - time: 20250708070700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250708074400
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250708080900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250708100200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250708133500
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250708141900
    name: 开水
    amount: 250
    unit: ml
  - time: 20250708155200
    name: 开水
    amount: 250
    unit: ml

  - time: 20250708191900
    name: 可可奶
    amount: 80.5
    unit: ml
  - time: 20250708205200
    name: 开水
    amount: 125
    unit: ml
med:
  - time: 20250708074400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250708080900
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20250708080900
    name: selenium
    amount: 200
    unit: μg
  - time: 20250708080900
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
