date: 20250718
food:
  - time: 20250718112300
    name: 梨
    amount: 251.0
    unit: g
  - time: 20250718112700
    name: 馒头2507b
    amount: 1
    unit: 个
  - time: 20250718112700
    name: 南瓜
    amount: 82.5
    unit: g
  - time: 20250718112700
    name: 卤牛肚2507a
    amount: 46.0
    unit: g
  - time: 20250718112700
    name: 芦笋
    amount: 176.0
    unit: g
  - time: 20250718115000
    name: 红塔玫瑰黄油饼
    amount: 25
    unit: g
  - time: 20250718115000
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250718115000
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250718115000
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250718111600
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250718111600
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250718174200
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250718174200
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250718155100
    name: 菊粉
    amount: 5.0
    unit: g
  - time: 20250718155100
    name: 百香果
    amount: 40
    unit: g

  - time: 20250718174500
    name: 李子
    amount: 150
    unit: g

  - time: 20250718174900
    name: 扬农沁香米
    amount: 40.0
    unit: g
  - time: 20250718174900
    name: 泉嫁艳青麦仁
    amount: 50.0
    unit: g
  - time: 20250718174900
    name: 菜心
    amount: 160
    unit: g
  - time: 20250718174900
    name: 胡萝卜
    amount: 180.0
    unit: g
  - time: 20250718174900
    name: 圣农冷冻原汁原味脆皮炸鸡
    amount: 100.0
    unit: g
    log:
      - 不预热、上下火、上层+180°C+15分钟
      - 翻面、上下火、上层+180°C+5分钟
  - time: 20250718174900
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250718174900
    name: 油
    amount: 0.5
    unit: g

  - time: 20250718181800
    name: 红塔玫瑰黄油饼
    amount: 25
    unit: g
  - time: 20250718181800
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250718181800
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
water:
  - time: 20250718095200
    name: 开水
    amount: 200
    unit: ml
  - time: 20250718105500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250718111600
    name: 咖啡
    amount: 83.5
    unit: ml
  - time: 20250718122300
    name: 开水
    amount: 250
    unit: ml

  - time: 20250718132800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250718150200
    name: 开水
    amount: 250
    unit: ml
  - time: 20250718154800
    name: 开水
    amount: 250
    unit: ml
  - time: 20250718181800
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250718191000
    name: 开水
    amount: 250
    unit: ml
med:
  - time: 20250718111600
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250718122300
    name: selenium
    amount: 200
    unit: μg
  - time: 20250718122300
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
