date: 20251203
food:
  - time: 20251203112300
    name: 苹果
    amount: 120
    unit: g

  - time: 20251203112800
    name: 塞北雪龙须挂面
    amount: 100
    unit: g
  - time: 20251203112800
    name: 卤牛肉2512a
    amount: 50
    unit: g
  - time: 20251203112800
    name: 西兰苔
    amount: 100
    unit: g
  - time: 20251203112800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g

  - time: 20251203115700
    name: 古丽琪果仁月饼
    amount: 0
    unit: g
  - time: 20251203115700
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251203115700
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251203115700
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251203122000
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251203122000
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20251203194000
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251203194000
    name: 东棘沙棘原浆
    amount: 30.0
    unit: g
  - time: 20251203194000
    name: 百香果
    amount: 48
    unit: g
  - time: 20251203194000
    name: 菊粉
    amount: 13.0
    unit: g

  - time: 20251203194200
    name: 柚子
    amount: 150
    unit: g

  - time: 20251203194900
    name: 扬农沁香米
    amount: 60.0
    unit: g
  - time: 20251203194900
    name: 紫米
    amount: 20.0
    unit: g
  - time: 20251203194900
    name: 绿豆
    amount: 10.0
    unit: g
  - time: 20251203194900
    name: 大成奥尔良味香煎鸡扒
    amount: 75
    unit: g
  - time: 20251203194900
    name: 木耳
    amount: 10.0
    unit: g
  - time: 20251203194900
    name: 象大厨北豆腐
    amount: 0
    unit: g
  - time: 20251203194900
    name: 油菜
    amount: 210
    unit: g
  - time: 20251203194900
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251203194900
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251203201200
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251203201200
    name: 兴科可可粉
    amount: 4.5
    unit: g
water:
  - time: 20251203095200
    name: 开水
    amount: 200
    unit: ml
  - time: 20251203110400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251203112800
    name: 汤水
    amount: 400
    unit: ml    
  - time: 20251203122000
    name: 咖啡
    amount: 120.0
    unit: ml
  - time: 20251203124700
    name: 开水
    amount: 250
    unit: ml
  - time: 20251203134300
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251203140800
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251203152800
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251203160700
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251203165800
    name: 红茶
    amount: 250
    unit: ml
  - time: 20251203201200
    name: 可可奶
    amount: 120.0
    unit: ml
  - time: 20251203202800
    name: 红茶
    amount: 130
    unit: ml
med:
  - time: 20251203122000
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251203124700
    name: selenium
    amount: 200
    unit: μg
  - time: 20251203124700
    name: mature multi
    amount: 1
    unit: 片
  - time: 20251203194000
    name: 维生素C
    amount: 1.0
    unit: g
log: |
comment: |
