date: 20251007
food:
  - time: 20251007082400
    name: 番石榴
    amount: 150
    unit: g

  - time: 20251007082700
    name: 馒头2510a
    amount: 1
    unit: 个
  - time: 20251007082700
    name: 卤猪舌2510a
    amount: 43
    unit: g
  - time: 20251007082700
    name: 炖排骨2510a
    amount: 40
    unit: g
  - time: 20251007082700
    name: 南瓜
    amount: 100
    unit: g
  - time: 20251007082700
    name: 秋葵
    amount: 130
    unit: g

  - time: 20251007084300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251007084300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251007084300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251007085100
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251007085100
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251007151200
    name: 番茄酱
    amount: 30.0
    unit: g
  - time: 20251007151200
    name: 域尚楼兰沙棘全果原浆
    amount: 50.0
    unit: g
  - time: 20251007151200
    name: 菊粉
    amount: 6.0
    unit: g

  - time: 20251007151400
    name: 香蕉
    amount: 130
    unit: g

  - time: 20251007151600
    name: 面团2505a
    amount: 130
    unit: g
  - time: 20251007151600
    name: 甘青精制小麦粉
    amount: 15
    unit: g
  - time: 20251007151600
    name: 牛佰仕马苏里拉奶酪
    amount: 50.0
    unit: g
  - time: 20251007151600
    name: 泰森轻食鸡胸肉排
    amount: 40
    unit: g
  - time: 20251007151600
    name: 三文鱼
    amount: 30.0
    unit: g
    log:
      - 披萨加奶酪、肉、在上层；
      - 不预热、上下火、140°C+30分钟；
      - 上下火、160°C+2分钟，月饼在下层.
  - time: 20251007151600
    name: 大白菜
    amount: 250
    unit: g
  - time: 20251007151600
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251007151600
    name: 油
    amount: 0.5
    unit: g

  - time: 20251007153000
    name: 我的童年纯牛奶粉
    amount: 20.0
    unit: g
  - time: 20251007153000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20251007184300
    name: 梨
    amount: 120
    unit: g

  - time: 20251007184500
    name: 红薯
    amount: 150
    unit: g
  - time: 20251007184500
    name: 松花鸭皮蛋
    amount: 50
    unit: g
  - time: 20251007184500
    name: 娃娃菜
    amount: 140
    unit: g
  - time: 20251007184500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251007184500
    name: 油
    amount: 0.5
    unit: g

  - time: 20251007190000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20251007190000
    name: 可可粉
    amount: 3.0
    unit: g
water:
  - time: 20251007071500
    name: 开水
    amount: 200
    unit: ml
  - time: 20251007081500
    name: 开水
    amount: 250
    unit: ml
  - time: 20251007085100
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251007093000
    name: 开水
    amount: 250
    unit: ml
  - time: 20251007101600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251007143400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251007153000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20251007160400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251007165100
    name: 开水
    amount: 250
    unit: ml
  - time: 20251007190000
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20251007193000
    name: 开水
    amount: 100
    unit: ml
med:
  - time: 20251007085100
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251007093000
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20251007093000
    name: selenium
    amount: 200
    unit: μg
  - time: 20251007093000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
