date: 20250716
food:
  - time: 20250716094000
    name: 梨
    amount: 270
    unit: g

  - time: 20250716094300
    name: 馒头2507b
    amount: 1
    unit: 个
  - time: 20250716094300
    name: 南瓜
    amount: 65
    unit: g
  - time: 20250716094300
    name: 康大熏香兔前腿
    amount: 65
    unit: g
  - time: 20250716094300
    name: 芦笋
    amount: 160
    unit: g

  - time: 20250716100300
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250716100300
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250716100300
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250716101600
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250716101600
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250716142700
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250716142700
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250716155100
    name: 百香果
    amount: 40
    unit: g

  - time: 20250716143000
    name: 扬农沁香米
    amount: 30.0
    unit: g
  - time: 20250716143000
    name: 福润东方有机小米
    amount: 20.0
    unit: g
  - time: 20250716143000
    name: 泉嫁艳青麦仁
    amount: 50
    unit: g
  - time: 20250716143000
    name: 油菜
    amount: 180
    unit: g
  - time: 20250716143000
    name: 木耳
    amount: 10
    unit: g
  - time: 20250716143000
    name: 腌鸡腿肉2507a
    amount: 50
    unit: g
  - time: 20250716143000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250716143000
    name: 油
    amount: 1.0
    unit: g

  - time: 20250716150000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250716150000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g    

  - time: 20250716190200
    name: 荔枝
    amount: 125
    unit: g

  - time: 20250716190800
    name: 土豆
    amount: 100
    unit: g
  - time: 20250716190800
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250716190800
    name: 香油臭豆腐乳
    amount: 10
    unit: g
  - time: 20250716190800
    name: 油菜
    amount: 120
    unit: g
  - time: 20250716190800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250716190800
    name: 油
    amount: 1.0
    unit: g

  - time: 20250716194800
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250716194800
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250716081700
    name: 开水
    amount: 200
    unit: ml
  - time: 20250716092400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250716101600
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20250716112700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250716142700
    name: 开水
    amount: 250
    unit: ml
  - time: 20250716150000
    name: 咖啡
    amount: 81.0
    unit: ml
  - time: 20250716161300
    name: 开水
    amount: 250
    unit: ml
  - time: 20250716180400
    name: 开水
    amount: 250
    unit: ml
  - time: 20250716194800
    name: 可可奶
    amount: 80.0
    unit: ml
  - time: 20250716183000
    name: 开水
    amount: 100
    unit: ml
med:
  - time: 20250716101600
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250716112700
    name: selenium
    amount: 200
    unit: μg
  - time: 20250716112700
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
