date: 20260111
food:
  - time: 20260111052300
    name: 番石榴
    amount: 220
    unit: g

  - time: 20260111052600
    name: 馒头2601a
    amount: 1
    unit: 个
  - time: 20260111052600
    name: 南瓜
    amount: 120
    unit: g
  - time: 20260111052600
    name: 粉蒸肉2601a
    amount: 70
    unit: g
  - time: 20260111052600
    name: 红菜苔
    amount: 150
    unit: g
  - time: 20260111052600
    name: 十三村原味腐乳
    amount: 10
    unit: g

  - time: 20260111054200
    name: 徽韵棠原味黄山烧饼
    amount: 10
    unit: g
  - time: 20260111054200
    name: 蛋挞2601a
    amount: 1
    unit: 个
  - time: 20260111054200
    name: 坚果切糕
    amount: 0
    unit: g
  - time: 20260111054200
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260111054200
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260111054200
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260111055500
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20260111055500
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20260111130400
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20260111130400
    name: 百香果
    amount: 20.0
    unit: g
  - time: 20260111130400
    name: 菊粉
    amount: 10.0
    unit: g
  - time: 20260111130400
    name: 维生素C
    amount: 2
    unit: g

  - time: 20260111130500
    name: 猕猴桃
    amount: 72.5
    unit: g
  - time: 20260111130500
    name: 金桔
    amount: 150
    unit: g

  - time: 20260111130800
    name: 红薯
    amount: 200
    unit: g
  - time: 20260111130800
    name: 炖娃娃鱼2601a
    amount: 60
    unit: g
  - time: 20260111130800
    name: 大白菜
    amount: 240
    unit: g
  - time: 20260111130800
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20260111130800
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260111132700
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20260111132700
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g
  - time: 20260111132700
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g
water:
  - time: 20260111041300
    name: 开水
    amount: 200
    unit: ml
  - time: 20260111051200
    name: 开水
    amount: 250
    unit: ml
  - time: 20260111055500
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20260111062000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260111072000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260111080000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260111090700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260111095500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260111132700
    name: 咖啡
    amount: 80.5
    unit: ml
  - time: 20260111135500
    name: 开水
    amount: 250
    unit: ml
  - time: 20260111165000
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20260111055500
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260111062000
    name: selenium
    amount: 200
    unit: μg
  - time: 20260111062000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |