date: 20260201
food:
  - time: 20260201074000
    name: 桔柚
    amount: 90
    unit: g

  - time: 20260201055300
    name: 馒头2601b
    amount: 1
    unit: 个
  - time: 20260201055300
    name: 卤牛肉2601a
    amount: 45
    unit: g
  - time: 20260201055300
    name: 南瓜
    amount: 90
    unit: g
  - time: 20260201055300
    name: 西洋菜
    amount: 130
    unit: g
  - time: 20260201055300
    name: 十三村原味腐乳
    amount: 8
    unit: g

  - time: 20260201061000
    name: 黄吉利苕丝糖
    amount: 20
    unit: g
  - time: 20260201061000
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260201061000
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260201061000
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260201061700
    name: 河套纯牛奶粉
    amount: 26.0
    unit: g
  - time: 20260201061700
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260201124100
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20260201124100
    name: 戈壁密码有机沙棘原浆
    amount: 30
    unit: g
  - time: 20260201124100
    name: 百香果
    amount: 70.0
    unit: g
  - time: 20260201124100
    name: 菊粉
    amount: 10
    unit: g

  - time: 20260201124200
    name: 猕猴桃
    amount: 60
    unit: g

  - time: 20260201124600
    name: 一品寒香大米
    amount: 75.0
    unit: g
  - time: 20260201124600
    name: 高粱米
    amount: 10.0
    unit: g
  - time: 20260201124600
    name: 红豆
    amount: 15.0
    unit: g
  - time: 20260201124600
    name: 腌鸡腿肉2601a
    amount: 80
    unit: g
    log:
      - 不预热、上层、上下火、190°C+15分钟
      - 翻面、200°C+5分钟。
  - time: 20260201124600
    name: 红薯叶
    amount: 250.0
    unit: g
  - time: 20260201124600
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20260201124600
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260201134400
    name: 河套纯牛奶粉
    amount: 25.0
    unit: g
  - time: 20260201134400
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g
water:
  - time: 20260201044000
    name: 开水
    amount: 200
    unit: ml
  - time: 20260201053700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260201061700
    name: 咖啡
    amount: 103.5
    unit: ml
  - time: 20260201074000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260201092700
    name: 开水
    amount: 250
    unit: ml
  - time: 20260201102300
    name: 开水
    amount: 250
    unit: ml
  - time: 20260201113300
    name: 开水
    amount: 250
    unit: ml
  - time: 20260201134400
    name: 咖啡
    amount: 100.0
    unit: ml
  - time: 20260201165100
    name: 开水
    amount: 250
    unit: ml
med:
  - time: 20260201061700
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260201074000
    name: selenium
    amount: 200
    unit: μg
  - time: 20260201074000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
