date: 20251029
food:
  - time: 20251029122600
    name: 猕猴桃
    amount: 65
    unit: g

  - time: 20251029122800
    name: 山楂
    amount: 20
    unit: g

  - time: 20251029123000
    name: 红薯
    amount: 120
    unit: g
  - time: 20251029123000
    name: 山药豆
    amount: 60
    unit: g
  - time: 20251029123000
    name: 卤牛肉2510c
    amount: 50
    unit: g
  - time: 20251029123000
    name: 南瓜
    amount: 75
    unit: g
  - time: 20251029123000
    name: 西兰花
    amount: 180
    unit: g

  - time: 20251029124500
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251029124500
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251029124500
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251029130200
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251029130200
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20251029193300
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251029193300
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20251029193300
    name: 菊粉
    amount: 5.0
    unit: g
  - time: 20251029193300
    name: 百香果
    amount: 45
    unit: g
  - time: 20251029193300
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20251029123000
    name: 扬农沁香米
    amount: 40
    unit: g
  - time: 20251029123000
    name: 紫米
    amount: 15
    unit: g
  - time: 20251029123000
    name: 绿豆
    amount: 10
    unit: g
  - time: 20251029123000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20251029123000
    name: 小白菜
    amount: 250
    unit: g
  - time: 20251029123000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251029123000
    name: 味精
    amount: 0.5
    unit: g
  - time: 20251029123000
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g


  - time: 20251029193500
    name: 柿子
    amount: 90
    unit: g

  - time: 20251029194300
    name: 全麦面包2510b
    amount: 80
    unit: g
  - time: 20251029194300
    name: 腌鸡膝软骨2510a
    amount: 80
    unit: g
  - time: 20251029194300
    name: 三文鱼
    amount: 0.0
    unit: g
  - time: 20251029194300
    name: 油菜
    amount: 150
    unit: g
  - time: 20251029194300
    name: 中盐绿色低钠湖盐
    amount: 1.5
    unit: g
  - time: 20251029194300
    name: 味精
    amount: 0.5
    unit: g
  - time: 20251029194300
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251029201400
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251029201400
    name: 兴科可可粉
    amount: 4.5
    unit: g
water:
  - time: 20251029111300
    name: 开水
    amount: 150
    unit: ml
  - time: 20251029121400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251029130200
    name: 咖啡
    amount: 121.5
    unit: ml
  - time: 20251029133800
    name: 开水
    amount: 250
    unit: ml
  - time: 20251029164300
    name: 开水
    amount: 250
    unit: ml
  - time: 20251029172700
    name: 开水
    amount: 250
    unit: ml
  - time: 20251029180300
    name: 开水
    amount: 250
    unit: ml
  - time: 20251029201400
    name: 可可奶
    amount: 120.0
    unit: ml
  - time: 20251029222600
    name: 开水
    amount: 120
    unit: ml
med:
  - time: 20251029130200
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251029133800
    name: selenium
    amount: 200
    unit: μg
  - time: 20251029133800
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
