date: 20250629
food:
  - time: 20250629085500
    name: 黄桃
    amount: 122
    unit: g

  - time: 20250629090000
    name: 馒头2506c
    amount: 1
    unit: 个
  - time: 20250629090000
    name: 南瓜
    amount: 40
    unit: g
  - time: 20250629190100
    name: 粉蒸肉2506b
    amount: 35
    unit: g
  - time: 20250629090000
    name: 芦笋
    amount: 115.0
    unit: g
  - time: 20250629090000
    name: 中盐绿色低钠湖盐
    amount: 0.5
    unit: g

  - time: 20250629093200
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250629093200
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250629093200
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250629094000
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250629094000
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250629140300
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250629140300
    name: 域尚楼兰沙棘全果原浆
    amount: 20
    unit: g
  - time: 20250629140300
    name: 艾斯蔗菊粉
    amount: 10
    unit: g

  - time: 20250629140400
    name: 杏
    amount: 196
    unit: g

  - time: 20250629140800
    name: 扬农沁香米
    amount: 35.0
    unit: g
  - time: 20250629140800
    name: 福润东方有机小米
    amount: 20.0
    unit: g
  - time: 20250629140800
    name: 泉嫁艳青麦仁
    amount: 40.0
    unit: g
  - time: 20250629140800
    name: 腌鸡腿肉2504b
    amount: 50
    unit: g
  - time: 20250629140800
    name: 木耳
    amount: 10
    unit: g
  - time: 20250629140800
    name: 油菜
    amount: 150
    unit: g
  - time: 20250629140800
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250629140800
    name: 油
    amount: 0.5
    unit: g

  - time: 20250629145800
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250629145800
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20250629185100
    name: 圣女果
    amount: 209
    unit: g
    log:
      - 糖珀琥104g
      - 青甜2号105g

  - time: 20250629185900
    name: 土豆
    amount: 150.0
    unit: g
  - time: 20250629185900
    name: 锦悦和五城茶干
    amount: 0
    unit: g
  - time: 20250629185900
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250629185900
    name: 油菜
    amount: 150
    unit: g
  - time: 20250629185900
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250629185900
    name: 油
    amount: 0.5
    unit: g

  - time: 20250629200500
    name: 河套全脂奶粉
    amount: 20.0
    unit: g
  - time: 20250629200500
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250629072800
    name: 开水
    amount: 200
    unit: ml
  - time: 20250629083100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250629094000
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250629104500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250629120600
    name: 开水
    amount: 250
    unit: ml
  - time: 20250629145800
    name: 咖啡
    amount: 80.0
    unit: ml
  - time: 20250629162000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250629185900
    name: 汤水
    amount: 500
    unit: ml
  - time: 20250629200500
    name: 可可奶
    amount: 91.0
    unit: ml
  - time: 20250629223200
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20250629094000
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250629104500
    name: selenium
    amount: 200
    unit: μg
  - time: 20250629104500
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
