date: 20260214
food:
  - time: 20260214054700
    name: 番石榴
    amount: 150
    unit: g

  - time: 20260214055100
    name: 塞北雪龙须挂面
    amount: 120.0
    unit: g
  - time: 20260214055100
    name: 猪蹄筋
    amount: 242.0
    unit: g
    log: 实际是猪元宝、猪窝骨
  - time: 20260214055100
    name: 胡萝卜
    amount: 118.0
    unit: g
  - time: 20260214055100
    name: 楚郡味豆瓣酱
    amount: 15.0
    unit: g
  - time: 20260214055100
    name: 黄心菜
    amount: 70
    unit: g
  - time: 20260214055100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260214055100
    name: 味精
    amount: 0.5
    unit: g

  - time: 20260214062400
    name: 凤城鸡仔饼
    amount: 18
    unit: g
  - time: 20260214062400
    name: 新疆手工切糕
    amount: 37
    unit: g
  - time: 20260214062400
    name: 徽韵棠原味黄山烧饼
    amount: 20
    unit: g
  - time: 20260214062400
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20260214062400
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20260214062400
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20260214064400
    name: 河套纯牛奶粉
    amount: 25.0
    unit: g
  - time: 20260214064400
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20260214140700
    name: 番茄酱
    amount: 25
    unit: g
  - time: 20260214140700
    name: 戈壁密码有机沙棘原浆
    amount: 25
    unit: g
  - time: 20260214140700
    name: 菊粉
    amount: 13.0
    unit: g

  - time: 20260214140800
    name: 猕猴桃
    amount: 70.5
    unit: g

  - time: 20260214141200
    name: 一品寒香大米
    amount: 60.0
    unit: g
  - time: 20260214141200
    name: 胡萝卜
    amount: 90
    unit: g
  - time: 20260214141200
    name: 韩三顺辣白菜
    amount: 40.0
    unit: g
  - time: 20260214141200
    name: 枸杞
    amount: 3.0
    unit: g
  - time: 20260214141200
    name: 楚郡味豆瓣酱
    amount: 6.0
    unit: g
  - time: 20260214115100
    name: 卤牛肉2601a
    amount: 50
    unit: g
  - time: 20260214115100
    name: 油菜
    amount: 230
    unit: g
  - time: 20260214115100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20260214115100
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20260214142700
    name: 黄吉利苕丝糖
    amount: 20
    unit: g
  - time: 20260214142700
    name: 河套纯牛奶粉
    amount: 26.5
    unit: g
  - time: 20260214142700
    name: 品儿Piner天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20260214043200
    name: 开水
    amount: 200
    unit: ml
  - time: 20260214052300
    name: 开水
    amount: 250
    unit: ml
  - time: 20260214055100
    name: 汤水
    amount: 500
    unit: ml
  - time: 20260214064400
    name: 咖啡
    amount: 101.0
    unit: ml
  - time: 20260214074000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260214084600
    name: 开水
    amount: 250
    unit: ml
  - time: 20260214103400
    name: 开水
    amount: 250
    unit: ml
  - time: 20260214112000
    name: 开水
    amount: 250
    unit: ml
  - time: 20260214142700
    name: 可可奶
    amount: 108.0
    unit: ml
  - time: 20260214154200
    name: 开水
    amount: 100
    unit: ml
med:
  - time: 20260214064400
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20260214074000
    name: 维生素D3
    amount: 125
    unit: μg
  - time: 20260214074000
    name: selenium
    amount: 200
    unit: μg
  - time: 20260214074000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
