date: 20250719
food:
  - time: 20250719112300
    name: 梨
    amount: 250
    unit: g

  - time: 20250719112700
    name: 扬农沁香米
    amount: 50
    unit: g
  - time: 20250719112700
    name: 南瓜
    amount: 82.5
    unit: g
  - time: 20250719112700
    name: 黑胡椒风味芊芊鱼排
    amount: 65
    unit: g
  - time: 20250719112700
    name: 芦笋
    amount: 150
    unit: g

  - time: 20250719115000
    name: 红塔玫瑰黄油饼
    amount: 50
    unit: g
  - time: 20250719115000
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20250719115000
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20250719115000
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20250719120900
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250719120900
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250719175500
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20250719175500
    name: 域尚楼兰沙棘全果原浆
    amount: 25
    unit: g
  - time: 20250719175500
    name: 菊粉
    amount: 8.0
    unit: g
  - time: 20250719175500
    name: 百香果
    amount: 42.0
    unit: g

  - time: 20250719130000
    name: 裕湘A+细挂面
    amount: 100
    unit: g
  - time: 20250719130000
    name: 鸡蛋
    amount: 45
    unit: g
  - time: 20250719130000
    name: 锦悦和五城茶干
    amount: 165
    unit: g
  - time: 20250719130000
    name: 菜心
    amount: 100
    unit: g
  - time: 20250719130000
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250719130000
    name: 香油
    amount: 1.0
    unit: g

  - time: 20250719182700
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250719182700
    name: 景兰冻干黑咖啡
    amount: 1.0
    unit: g

  - time: 20250719175000
    name: 李子
    amount: 167.5
    unit: g

  - time: 20250719175500
    name: 馒头2507c
    amount: 1
    unit: 个
  - time: 20250719175500
    name: 胡萝卜
    amount: 180
    unit: g
  - time: 20250719175500
    name: 油菜
    amount: 200
    unit: g
  - time: 20250719175500
    name: 粉蒸肉2507b
    amount: 60
    unit: g
  - time: 20250719175500
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20250719175500
    name: 油
    amount: 0.5
    unit: g

  - time: 20250719190000
    name: 红塔玫瑰黄油饼
    amount: 50
    unit: g
  - time: 20250719190000
    name: 奶粉
    amount: 20.0
    unit: g
  - time: 20250719190000
    name: 天然可可粉
    amount: 3.0
    unit: g
water:
  - time: 20250719095200
    name: 开水
    amount: 200
    unit: ml
  - time: 20250719105500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250719120900
    name: 咖啡
    amount: 83.5
    unit: ml
  - time: 20250719131000
    name: 开水
    amount: 250
    unit: ml
  - time: 20250719134500
    name: 开水
    amount: 250
    unit: ml
  - time: 20250719182700
    name: 咖啡
    amount: 80
    unit: ml
  - time: 20250719195100
    name: 开水
    amount: 250
    unit: ml
  - time: 20250719190000
    name: 可可奶
    amount: 80
    unit: ml
med:
  - time: 20250719120900
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20250719131000
    name: selenium
    amount: 200
    unit: μg
  - time: 20250719131000
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
