date: 20251102
food:
  - time: 20251102133000
    name: 猕猴桃
    amount: 65
    unit: g
  - time: 20251102133100
    name: 柿子
    amount: 70
    unit: g

  - time: 20251102133500
    name: 红薯
    amount: 78.0
    unit: g
  - time: 20251102133500
    name: 山药豆
    amount: 40.5
    unit: g
  - time: 20251102133500
    name: 馒头2510c
    amount: 1
    unit: 个
  - time: 20251102133500
    name: 广信酱油鲭鱼
    amount: 80
    unit: g
  - time: 20251102133500
    name: 南瓜
    amount: 85
    unit: g
  - time: 20251102133500
    name: 秋葵
    amount: 130
    unit: g

  - time: 20251102135500
    name: 如紫兰果仁月饼
    amount: 0
    unit: g
  - time: 20251102135500
    name: 盼月枣肉核桃老月饼
    amount: 0
    unit: g
  - time: 20251102135500
    name: 麦胚芽
    amount: 15.0
    unit: g
  - time: 20251102135500
    name: 亚麻籽粉
    amount: 10.0
    unit: g
  - time: 20251102135500
    name: 浙梅免洗桑葚
    amount: 10.0
    unit: g

  - time: 20251102141700
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251102141700
    name: 景兰冻干黑咖啡
    amount: 1.5
    unit: g

  - time: 20251102185900
    name: 番茄酱
    amount: 30
    unit: g
  - time: 20251102185900
    name: 域尚楼兰沙棘全果原浆
    amount: 50
    unit: g
  - time: 20251102185900
    name: 菊粉
    amount: 10.0
    unit: g
  - time: 20251102185900
    name: 百香果
    amount: 50
    unit: g
  - time: 20251102185900
    name: 臻妍益生菌冻干粉2509
    amount: 3.0
    unit: g

  - time: 20251102190100
    name: 全麦面包2510b
    amount: 100
    unit: g
  - time: 20251102190100
    name: 三文鱼
    amount: 60
    unit: g
  - time: 20251102190100
    name: 油菜
    amount: 250
    unit: g
  - time: 20251102190100
    name: 中盐绿色低钠湖盐
    amount: 1.0
    unit: g
  - time: 20251102190100
    name: 欧丽薇兰橄榄油
    amount: 0.5
    unit: g

  - time: 20251102235000
    name: 奶粉
    amount: 30.0
    unit: g
  - time: 20251102235000
    name: 兴科可可粉
    amount: 4.5
    unit: g
water:
  - time: 20251102121200
    name: 开水
    amount: 150
    unit: ml
  - time: 20251102131400
    name: 开水
    amount: 250
    unit: ml
  - time: 20251102141700
    name: 咖啡
    amount: 120.5
    unit: ml
  - time: 20251102144700
    name: 开水
    amount: 250
    unit: ml
  - time: 20251102155600
    name: 开水
    amount: 250
    unit: ml
  - time: 20251102162900
    name: 开水
    amount: 250
    unit: ml
  - time: 20251102155700
    name: 汤水
    amount: 500
    unit: ml
  - time: 20251102235000
    name: 可可奶
    amount: 120.0
    unit: ml
  - time: 20251102001000
    name: 开水
    amount: 50
    unit: ml
med:
  - time: 20251102141700
    name: 楚牛牛磺酸
    amount: 0.5
    unit: g
  - time: 20251102144700
    name: selenium
    amount: 200
    unit: μg
  - time: 20251102144700
    name: mature multi
    amount: 1
    unit: 片
log: |
comment: |
