date: 20251214
sleep: 
  time: 20251208152000
  weight: 54.9
wake:
  time: 20251214022600
  weight: 53.3
  SpO2: 94
  PRbpm: 62
  log: |
    补水0次，睡觉中间起来小便3次。
exercise: 
- time: 20251214025000
  item:
  - type: 大拉伸(Greatest Stretch)
    amount: 1
    unit: turn
  - type: 坐姿转体扭腰(Core Twist) 
    amount: 20
    unit: turn
  - type: 超人敬礼*5 + 鸟狗式(birddog)*10 + 俯卧撑(push-ups)*5
    amount: 2 
    unit: set
  - type: 仰卧直腿触足卷腹(straight leg toe touches)*10 + 坐位体前屈(Sit and Reach)*10
    amount: 5
    unit: set
  - type: 腹部拉伸(Cobra Pose) + 颈部拉伸*5
    amount: 5
    unit: set
  SpO2: 98
  PRbpm: 96
  endheartrate: 95
  log: |
    室内运动后把脉: 寸脉关脉中偏浅、尺脉深度中；侧向居中；三处清晰有力。
- time: 20251214234000
  item:
  - type: walk
    amount: 180
    unit: minute
  SpO2: 96
  PRbpm: 115
- time: 20251214230000
  item:
  - type: 臀腰激活L2
    amount: 14
    unit: minute
  SpO2: 97
  PRbpm: 87
stool:
- time: 20251214210000
  amount:   2   #	1:多; 2:适中;	3:少
  type:     2   #	0:水样; 1:软;	2:适中;	3:硬;
  diffcult: 1   #	1:不困难;	2:困难
log:
comment:
