date <- c()
PRbpm1 <- c()
PRbpm2 <- c()
PRbpm3 <- c()
endheartrate <- c()
plot(c(1:0),PRbpm1,type="s",col="red",xaxt="n",xlab = "date",ylab="heart rate",ylim=range(50:160))
lines(c(1:0),PRbpm2,type="s",col="blue")
lines(c(1:0),PRbpm3,type="s",col="gold")
lines(c(1:0),endheartrate,type="s",col="green")
legend("topleft",inset=.05,title="心率曲线",c("起床血氧仪(辅助线:50~65)","运动后血氧仪","运动后把脉","散步后血氧仪"),lty=c(1,1,1,1),col=c("red","blue","green","gold"))
abline(h = 65,col="red",lty = 3)
abline(h = 50,col="red",lty = 3)
axis(1, c(1:0),date)
