date <- c()
sleep <- c()
wake <- c()
sleeplong <- c()
plot(c(1:0),sleep,type="b",pch=15,lty=1,col="red",xaxt="n",xlab = "date")
lines(c(1:0),wake,type="b",pch=17,lty=2,col="blue")
lines(c(1:0),sleeplong,type="b",pch=21,lty=2,col="green")
legend("topleft",inset=.05,title="睡眠曲线",c("睡","醒","时长"),lty=c(1,2,2),pch=c(15,17,21),col=c("red","blue","green"))
axis(1, c(1:0),date)
